### ISSUE TITLE
Have option to view the pdf and preview the pdf without downloading it

### ISSUE THREAD

**Issue by brendanheywood** [mdjnelson/moodle-mod_customcert#153]
From the students point of view I should be able to either view the pdf or download it. If you view it then it just loads in the browser without downloading it, and you can print it directly from there. Forcing a download is a bit ugly especially on some devices when you just want to see it. This way the back button still works and you can see if without having to try and view the pdf is some other software.

Likewise for a course manager there should be a preview which does exactly the same thing, and after making changes you can just reload the page and get the new pdf without forcing a clunky download.

Both of these should be a http get not a post, we don't need a sesskey here and we want to be able to reload the page and deep link to them.

**Comment by emmarichardson** [comment]
+1 for this.

**Comment by ahmadf20** [comment]
Hi, is there any update on this?

**Comment by mdjnelson** [comment]
Apologies, but no. If you can create a patch I can review that would be great.

**Comment by brendanheywood** [comment]
I've got a patch for this:

https://github.com/mdjnelson/moodle-mod_customcert/pull/388/files

**Comment by brendanheywood** [comment]
Also I have added a new option, I've just changed the download to be inline. You can always save it from an inline preview but the other way around so I think this is the better way than adding two similar options.

Also @mdjnelson you travis build looks pretty unhappy?

**Comment by mdjnelson** [comment]
Thanks Brendan.

Hmm, will investigate the Travis errors. These complaints look new, don't think I had it last push.

**Comment by mdjnelson** [comment]
Merged. Thanks!
