### ISSUE TITLE
Feature Request: Relative Expiration Date Element

### ISSUE THREAD

**Issue by michael-milette** [mdjnelson/moodle-mod_customcert#195]
Would it be possible to add an expiration date element? The way I envision it, you would add the element to a certificate and be prompted for the number of days after the completion date that the expiry date should be.

For example, if I set the expiry element to 365 days and the course completion date was today (2018-06-04), the element would display an expiry date of 2019-06-04. Naturally the date format should be determined by the language settings and not hard coded. The date format used here was just an example but one that I would probably be using.

Taking it one step further, it would be even better if you also choose a period from a dropdown list of "Days", "Weeks", "Months" and "Years" in addition to the number.

A second phase "nice to have" would be if the plugin could email out reminders "X" days before (negative number) or after (positive number) the expiration date with a custom message. However, for now, I would be very happy just to be able to include a relative expiry date.

Best regards,

Michael

**Comment by hjacob05** [comment]
Yes, to both these features. An expiration date feature as well as a reminder feature would be invaluable.

**Comment by atljohnsen** [comment]
I would welcome these features, as there are more and more positions in companies today that need re-sertification, and it would be highly valuable to be notified by email before their certificate expires.

**Comment by beast2013** [comment]
Needing the first part of your request myself, I used the Date element plugin as a template and created an Expiration Date element plugin. Its available at: https://github.com/beast2013/moodle-mod_customcert_element_expirationdate

**Comment by nkuehn** [comment]
We pondered this too and went for a simple "valid for two years" string in the generated certificate. 
From a broader perspective the proposed functionalities here are similar to what moodle has built in with badges.  Badges have an expiration, are verifiable online, can be bound to grading results etc. 
Maybe a more powerful approach could be to allow binding the generation of custom layouted certificates to the badges feature so the participants get the digital OpenBadge and the PDF certificate at once, following the same logic and including reliably identical expiration, ID, verification etc.

**Comment by michael-milette** [comment]
What I think is needed are a rectification reminder component.

Also, many businesses don't like the badges. They want to have custom looking certificates.

Certificates have also started to be used to demonstrate completion of external courses. Her is how we make it work:

1) You enrol in the course.
2) You get access to instructions and a URL which takes you to the third party course.
3) When you are done, you are expected to come back to the original site and upload the PDF of your certificate as an assignment.
4) Someone takes a peek at your certificate and marks the assignment as completed.

While I suppose you could do something similar by uploading your badge, accessing the metadata hidden inside it is much more challenging.

So, as you can see, I believe there is still a need for certificates.

**Comment by nkuehn** [comment]
@michael-milette  sorry for wording it obviously unclear:  I primarily want certificates (that's why I'm here!) and have my doubts about badges usefulness.  But I also know from painful experience with various software solutions that it's mid-term usually better to use the core product's logic and features as much as possible instead of replicating it in just gradually different plugins.    

That's why I would find it attractive to leverage the core moodle logic for granting and expiring badges to generating custom generated certificates using this plugin, which is amazing for the actual PDF generation but not as powerful and polished as badges when it comes to configuring e.g. how the emails are sent, when exactly who gets a certificate, tracking who has them and when they expire etc.

**Comment by mdjnelson** [comment]
https://github.com/mdjnelson/moodle-mod_customcert/pull/389 added expiry dates but it is quite limited with only being able to select 1, 2, 3, 4 or 5 years.

**Comment by michael-milette** [comment]
I have never come across it personally but I would imagine that some certifications might only be valid for 90 days or 6 months, especially in specialized fields or where information changes rapidly.

FYI: Other than that, the most common request that I get is actually from clients hosting in-person classes or online courses where teachers prefer to hand out physical certificates at the end of the last class or send them to learners by way of snail mail.  This is sometimes due to students not having access to a printer or because there might be some additional criteria not in the LMS that need to be considered before issuing a certificate. However, this is unrelated to this particular ticket.

Thanks again!

Michael

**Comment by mdjnelson** [comment]
Hi Michael, are you using the functionality introduced in https://github.com/mdjnelson/moodle-mod_customcert/pull/389 but just want to make it more flexible or were you unaware that this feature was implemented already?

**Comment by michael-milette** [comment]
I was unaware.
