### ISSUE TITLE
Feature Request: Student name in Capital Letters 

### ISSUE THREAD

**Issue by adanisyrex** [mdjnelson/moodle-mod_customcert#199]
Hi Everyone,

Would be possible to add a feature to the field of the student name to force the printing of it in the certificate using capital letters no matter how the name of the student is written in its profile?
Thanks a lot for our efforts!

**Comment by mdjnelson** [comment]
I am closing this as it is very specific and there are not many requests for it. If you wanted to do this change you can simply add `strtoupper()` in the student name element.

**Comment by adanisyrex** [comment]
ok, thanks, I will try

**Comment by mdjnelson** [comment]
The code would go in `https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_38_STABLE/element/studentname/classes/element.php`, just wrap `strtoupper` around `fullname`.

**Comment by adanisyrex** [comment]
Wonderful! Works perfectly, thank you so much!! You are great!

**Comment by mdjnelson** [comment]
Great to hear! :)

**Comment by adanisyrex** [comment]
Hi Mark, I was experimenting some issues with the "accent mark" so I was reading a little about it and finally I was leaving the code adding  " mb_strtoupper(fullname($user),'UTF-8')); " and it is working also with the accent...you know...in Spain we have those stuffs on the letters...
Well, I wanted to let you know in case you get the same question from other spaniard :), and... by the way I saw in your profile you are in BCN now...good place you choose! well, if you go down to Alicante give me a knock and you are invited to a perfect Paella done over fire in the Alicante Mountain :) Cheers and thanks again!

**Comment by mdjnelson** [comment]
Haha I'll take you up on that! :)
