### ISSUE TITLE
Custom certificate report is not showing verify code

### ISSUE THREAD

**Issue by darevalovelasquez** [mdjnelson/moodle-mod_customcert#264]
*DESCRIPTION*
The csv report of custom certificate activity is not showing the field CODE when the admin or teacher download the csv file of all user who acquired the certificate.

*STEPS TO REPLICATE*

As administrator or Teacher role

1- Go to the course with custom certificate module.

2- Enter to the custom certificate activity.

3- Go to "edit custom certificate"

4- Make sure the element "Code" is enabled on the certificate.

5- Save and return to the main menu of course and then enter to the custom certificate activity again.

6- Try to download the report as csv, xlsx.

7 - Open the file.

8 - Check there is only 2 fields, "Full name" and "awarded on"

9- There is no 3rd field called "Code".

OBSERVED BEHAVIOR:
There is no the field called "Code" that is useful to verify the certificate is authentic.

EXPECTED BEHAVIOR:
The 3rd field on the file downloaded must appear "Code"

*REPLICATION LOCATIONS*
Production sites with 3.5:
https://campus.euroidiomas.edu.pe/mod/customcert/view.php?id=19483
https://campus.euroidiomas.edu.pe/mod/customcert/view.php?id=38077

Sandboxsites with 3.5:

http://euroidiomas-sandbox.mrooms.net/mod/customcert/view.php?id=5
https://euroidiomasperu-sandbox.mrooms.net/mod/customcert/view.php?id=419
http://dvelasquez-sandbox.mrooms.net/mod/customcert/view.php?id=2114

*ADDITIONAL INVESTIGATION NOTES*

1-This feature is working fine on 3.4 openlms sites. example:
http://qa2mp2-sandbox.mrooms.net/mod/customcert/report.php?id=68481

2 - At least it must be one student enrolled on the course who adquired the certificate before the teacher or admin download the report on csv or xlsx.

Version of mod_customcert used in 3.4 MP2: 2017111301
Version of mod_customcert used in 3.5: 2018051704

*CLIENT IMPACT*

They need to watch this code list of users because the university require that information on the report.

**Comment by markn86** [comment]
This was done intentionally as not all Moodle users would know what the 'code' referred to and may not be relevant to them. You can still verify codes, they just don't appear on that page.

**Comment by sarahactiveops** [comment]
Hi all, just wondering if this was likely to progress please? We have upgraded to 3.6.3 and ideally need the code to appear in our csv report for big batches of certificates.

Thanks very much- absolutely love this plug in, it works well for our needs, the added benefit of the report would be super.
Cheers
Sarah

**Comment by markn86** [comment]
It's on my to-do list.

Note - I no longer work for Moodle and have moved onto developing other software. So, if someone was to fund the development that would speed things along. :)

**Comment by sarahactiveops** [comment]
Thanks Mark, much appreciated.

**Comment by mdjnelson** [comment]
I decided to just readd the column where it was before, quick fix. A better approach would be to have a hook that allows elements to add their own columns but that can be done in the future (if at all).

**Comment by apefive** [comment]
hello thanks! 
will you re-add the 'code' column for the 3.7.2, 3.6.3, 3.5.8 too? (especially for the last one that is actually the LTS).

**Comment by mdjnelson** [comment]
Yep, will do. Maybe this weekend.

**Comment by mdjnelson** [comment]
I am only supporting 3.8, 3.7 and 3.6 though, so you will have to cherry-pick (or manually apply) the patch if you are using an earlier version.

**Comment by apefive** [comment]
> I am only supporting 3.8, 3.7 and 3.6 though, so you will have to cherry-pick (or manually apply) the patch if you are using an earlier version.

thanks for replying ... I'm not sure I do or I'm not able to do :(
