### ISSUE TITLE
Custom certificate template error when adding Teacher field

### ISSUE THREAD

**Issue by dipakburnwal** [mdjnelson/moodle-mod_customcert#273]
Hello Mark,
Got an error while I was building a template for the Custom Certificate. Error occurred when I was adding the Teacher name field. This is the error that popped up on to the screen

"Coding error detected, it must be fixed by a programmer: Context does not belong to any course"

===============================
Debug info: 
Error code: codingerror
Stack trace:
line 5393 of /lib/accesslib.php: coding_exception thrown
line 1385 of /lib/enrollib.php: call to context->get_course_context()
line 1305 of /lib/enrollib.php: call to get_enrolled_join()
line 1353 of /lib/enrollib.php: call to get_enrolled_with_capabilities_join()
line 1476 of /lib/enrollib.php: call to get_enrolled_sql()
line 109 of /mod/customcert/element/teachername/classes/element.php: call to get_enrolled_users()
line 45 of /mod/customcert/element/teachername/classes/element.php: call to customcertelement_teachername\element->get_list_of_teachers()
line 67 of /mod/customcert/classes/edit_element_form.php: call to customcertelement_teachername\element->render_form_elements()
line 204 of /lib/formslib.php: call to mod_customcert\edit_element_form->definition()
line 79 of /mod/customcert/edit_element.php: call to moodleform->__construct()
============================

I'm using the 3.5 version of Moodle and 2018051704 version of the plugin. Thank you so much for helping.

**Comment by markn86** [comment]
Are you able to update to version 2018051707 and see if it still remains an issue?

**Comment by mdjnelson** [comment]
I was not able to replicate this issue.
