### ISSUE TITLE
Custom Cert returning Null Array on List

### ISSUE THREAD

**Issue by dustinbrisebois** [mdjnelson/moodle-mod_customcert#280]
We have a Customer who uses Totara 11 (Moodle 3.2) where the certificate list was showing no certificates have been provided (although some have been emailed out). 

When I went through, I found that in classes/certificate.php the get_issues function was returning null, it appears that the function get_conditional_issues_sql was returning no such users (including managers/admins) from the certificate list. 

This was resolved by adding:

`        if (empty($params)) {
            $params = Array($USER->id);
        }
`

on line 338 of certificate.php (again 3.2 branch). where the array then cannot return null; forcing the report to return the certificate pool list. This may result in unexpected behaviors but it does resolve the issue we are having with no data returned.

**Comment by mdjnelson** [comment]
Sorry, I am not able to replicate this and since this is happening on Totara I suggest discussing it with your host. :)
