### ISSUE TITLE
Custom Certificate (Customizing the Verification Result)

### ISSUE THREAD

**Issue by jepoyrn** [mdjnelson/moodle-mod_customcert#311]
I would like to ask help from all of you to please help me customized the Verification Result Page of the Verify Link of the Custom Certificate. I would like to add a custom field information to the result of the verification page like Membership Status: Active, Suspended or Revoked.

I already add the Custom Profile Field: Membership Status in the Member's/Student's Profile.

Please see attached picture.

Thank you very much in advance for the helps.
![1](https://user-images.githubusercontent.com/53229833/68088722-db457580-fe72-11e9-878e-d0c123b87fb4.PNG)

**Comment by mdjnelson** [comment]
Please don't ask support questions here. Please use https://moodle.org/mod/forum/view.php?id=7163.

In this case you need to pass the information to the template to use. See `export_for_template()` in https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_37_STABLE/classes/output/verify_certificate_result.php. These get passed to the template.
