### ISSUE TITLE
Use of subplugins.php has been deprecated in Moodle 3.8

### ISSUE THREAD

**Issue by mudrd8mz** [mdjnelson/moodle-mod_customcert#312]
Testing the latest version with to be released Moodle 3.8 shows debugging notice:
```
Use of subplugins.php has been deprecated. Please update your '/opt/app/mod/customcert' plugin to provide a subplugins.json file instead.
```

**Comment by mudrd8mz** [comment]
Subplugins should now be defined using /db/subplugins.json instead of /db/subplugins.php

**Comment by mdjnelson** [comment]
Thanks for the report. Please feel free to submit a patch if you can.

**Comment by mudrd8mz** [comment]
Thank you @mdjnelson I'm happy to submit a pull request. However, I am slightly confused with the branches setup in your repository. I did not find a master branch where I suppose this new 3.8-only feature should be added to. The latest branch seems to be MOODLE_37_STABLE, whereas I need something for 3.8. Thanks in advance for a guidance.

**Comment by mdjnelson** [comment]
Hi David, will create a 3.8 branch and ping you on here when done. I aim for some time next week (currently I am busy working (non-Moodle related) and on the weekend am moving to a new apartment).

**Comment by mdjnelson** [comment]
Hey David, I just created a 3.8 branch.

**Comment by mdjnelson** [comment]
Pinging @mudrd8mz in case no email was sent.

**Comment by mudrd8mz** [comment]
It was. Sorry for not getting to a reply yet. Thanks, I'll hopefully get to this next week.

**Comment by mdjnelson** [comment]
Thanks David. Once done let me know and ill push it upstream and release a new version on the plugins DB for 3.8.

**Comment by mdjnelson** [comment]
Once I looked into this it didn't involve much, so just did it quickly while I am on the computer. Cheers!

**Comment by mudrd8mz** [comment]
Oh nice! Thank you Mark
