### ISSUE TITLE
Permissions needed to manage templates

### ISSUE THREAD

**Issue by xisberto** [mdjnelson/moodle-mod_customcert#319]
In our school we want to give certain roles permission to manage the general settings and/or templates for mod_customcert.

Which permissions should we enable to make the plugin settings page appear to a user?

**Comment by mdjnelson** [comment]
This question should be asked on the moodle.org forums, at https://moodle.org/mod/forum/view.php?id=7163. I do not believe there is one specifically for that, see https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_38_STABLE/manage_templates.php.
