### ISSUE TITLE
support for RTL languages 

### ISSUE THREAD

**Issue by baraaabdelhady** [mdjnelson/moodle-mod_customcert#325]
the plugin does not support RTL languages like Arabic

**Comment by mdjnelson** [comment]
Can you please provide some replication steps?

**Comment by mohamedmohamedatia** [comment]
@Baraa, 
if you are talking about Arabic This is a font issue to solve it, 
1. Create a font folder inside moodledata, 
2. Download all fonts here  https://sourceforge.net/projects/tcpdf/ . as the tcpdf  is used to generate PDF. 
3. Choose a font named Arabiya which will support Arabic. 
there are many other fonts will be added as well , check the screenshot below 

![image](https://user-images.githubusercontent.com/30835105/75132738-2b2d9e00-56e9-11ea-9e26-8413eb57f0fa.png)

**Comment by mohamedmohamedatia** [comment]
DON'T Download the min version, download the fonts file the second one in the screenshot 
https://sourceforge.net/projects/tcpdf/files/
also I attached it here 

[tcpdf_fonts_6_3_2.zip](https://github.com/mdjnelson/moodle-mod_customcert/files/4243367/tcpdf_fonts_6_3_2.zip)


![image](https://user-images.githubusercontent.com/30835105/75133284-371a5f80-56eb-11ea-8522-412d060ca377.png)

**Comment by mdjnelson** [comment]
What exactly is the issue?

**Comment by mohamedmohamedatia** [comment]
When dynamic text fields are in Arabic such as course name or student name, it displayed correctly when we are previewing as HTML while we reposition the elements. but when we export it to PDF all Arabic characters are displayed as Questionmarks like ?????? ???? ?????. 

in my system, I was able to fix this by adding all tcpdf fonts in the font directory inside the Moodle data folder as I described above.

**Comment by mdjnelson** [comment]
Ah yes, I already knew this. Not all fonts support all UTF-8 characters. I am closing this.

**Comment by abdulrehmanbinaltaf** [comment]
@mohamedmohamedatia try to use "Free Mono" or "Free Serif",  default font and Arabic /URDU will work.
Free Mono
![image](https://archive.org/download/free_mono/free_mono.jpg)
Free Serif
![image](https://archive.org/download/free_mono/free_sherif.jpg)
