### ISSUE TITLE
Users can Update certificate

### ISSUE THREAD

**Issue by mohamedmohamedatia** [mdjnelson/moodle-mod_customcert#327]
I recommend to add an option to prevent or allow user data to be updated updated in the certificate. for example.
if we set it to prevent. when user awarded the certificate. After that he changed his Name. the Name on the certificate is not changed. 

we found some users changed their names to print a certificate to their friends. 

if he wants to update the data on the certificate, he should contact the admin so that he deleted the old one and new one is generated with the new updates. this will reduce the miss use of the certificate. 

as work around we temporarily locked the user name fields in the profile

**Comment by mdjnelson** [comment]
This would be solved by #38. Feel free to provide a patch.
