### ISSUE TITLE
Foreign keys violations.

### ISSUE THREAD

**Issue by ewallah** [mdjnelson/moodle-mod_customcert#331]
2 foreign keys on tables customcert and table customcert_pages point to a non-existent table customcert_template. Both keys should point to customcert_template**s**.  The missing letter surely affects performance, but is probably also the cause for other unwanted behaviour.

To check: visit admin/tool/xmldb and opt for the last option [check foreign keys]

```
- Foreign key template on table customcert points to a non-existent table customcert_template.
- Foreign key template on table customcert_pages points to a non-existent table customcert_template.
```

To fix in new installs: edit db/install,xml
```
-<KEY NAME="template" TYPE="foreign" FIELDS="templateid" REFTABLE="customcert_template" REFFIELDS="id"/>
+<KEY NAME="template" TYPE="foreign" FIELDS="templateid" REFTABLE="customcert_templates" REFFIELDS="id"/>

- <KEY NAME="template" TYPE="foreign" FIELDS="templateid" REFTABLE="customcert_template" REFFIELDS="id"/>
+ <KEY NAME="template" TYPE="foreign" FIELDS="templateid" REFTABLE="customcert_templates" REFFIELDS="id"/>
```
Current users will need an upgrade script so these changes get into the database.

**Comment by mdjnelson** [comment]
Fixed. Thanks. However, Moodle does not respect foreign keys and simply adds an index due to some historical reason where some or one database didnt support it. However, best to fix it now before it causes an issue later.

**Comment by ewallah** [comment]
THX for the quick response!
