### ISSUE TITLE
PDF generated without name

### ISSUE THREAD

**Issue by dipakburnwal** [mdjnelson/moodle-mod_customcert#333]
Hi,
Thank you for giving us such a great module. I am recently getting one weird issue when downloading the certificate. it works great with english language but when it comes to arabic the certificate is getting downloaded as pdf but without any name. it would be great if you could look into the issue. the name field in database table "customcert" for arabic holds this value "الشهادة"

Thanks, Dipak

**Comment by dipakburnwal** [comment]
Hi,

It would be really grateful if you could please look into this issue.
 
Thanks, Dipak

**Comment by dipakburnwal** [comment]
Hi,

Really appreciate if you could look into the issue.

Thanks, Dipak

**Comment by mdjnelson** [comment]
Hi dipakburnwal,

I will check this once I get some time.

Note - I do not get paid to work on this plugin and can only work on it in my spare time. Right now I am currently busy finishing other project work.

I suggest in the meantime renaming the certificate.

Thanks for your patience.

Regards,

Mark.

**Comment by dipakburnwal** [comment]
Thank you Mark, really appreciate

**Comment by mdjnelson** [comment]
Ok, I was able to replicate this.

**Comment by mdjnelson** [comment]
Seems this is an issue with the TCPDF library. Moodle is not cleaning the filename the TCPDF library is. When it passes the filename to `$pdf->Output($filename, 'D');' it becomes empty.

**Comment by mdjnelson** [comment]
Created a fix. Closing.
