### ISSUE TITLE
Problem for one specific certificate to access template records

### ISSUE THREAD

**Issue by MomentStorm** [mdjnelson/moodle-mod_customcert#334]
We recently updated to Moddle 3.6.6 (Build: 20190909) and custom certificate v. 3.6.3. For virtually all of the courses we have in our installation there was no problem with the upgrade. However, in one course we are getting an error message: "Can't find data record in database table customcert_templates", Neither students nor administrators can retrieve the certificates for this course. 

Since we have had found or had reports of an issue with any of the other 50 courses we upgraded I am not sure how to proceed with this. If I go into the Custom Certificate settings and choose manage templates I am linked to the correct template. We have also created new certificates for newly added courses w/o issue and using the existing template. 

Please let me know what next steps you suggest to troubleshoot and resolve this issue. Thanks!

**Comment by mdjnelson** [comment]
Do you have database access and are you also able to turn on debugging on your Moodle site so I can see a full stacktrace of the error? See https://docs.moodle.org/38/en/Debugging.

**Comment by MomentStorm** [comment]
Hi - sorry about the slow response. Busy couple of weeks. I actually resolved the issue in the main location by adding a new instance of the certificate. I have removed the older version but I think I was able to replicate the issue on one of my alternate installations. I will get you access info and turn on debugging so you can have a look. Give me a day or two to sort that out. Thanks!

**Comment by mdjnelson** [comment]
Would be interested in seeing replication steps for this, or being able to close it if you can't. :)

**Comment by MomentStorm** [comment]
Sorry Mark - Shouldn't have left you hanging for so long. Busy time.

While the main instance was corrected by deleting the certificate activity for this one course and then adding it back in as a new resource/activity, I do have an instance in our secondary site where the issue is still happening.  Can you give me your email address so I can create an account for you in that Moodle install. We make limited use of that install so I am happy to give you access to the site as an admin and to arrange database access as well.  Thanks!

**Comment by mdjnelson** [comment]
Sorry @MomentStorm I don't debug individual sites due to the risk of revealing sensitive information or if something was to happen and me being liable for damages etc etc. Were you able to turn on debugging and visit the page again that is throwing the area? It would be nice to see what line of code in the Custom certificate is causing that exception.

**Comment by MomentStorm** [comment]
Sure Mark - whatever you like. I'll try and get this done for you in the next couple of days. 
Cheers!

**Comment by MomentStorm** [comment]
Finally through my busy support time and getting caught up on this. Here are the steps I take and the debugging info I see:
Step: When logged in as site admin I select the custom certificate link to see what certificates have been issued. Here are the messages I see with debugging on:

Can't find data record in database table customcert_templates.
More information about this error

×Debug info: SELECT * FROM {customcert_templates} WHERE id = ?
[array (
0 => '5',
)]
Error code: invalidrecord


×Stack trace:
line 1546 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
line 1522 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
line 33 of /mod/customcert/view.php: call to moodle_database->get_record()

Hope that is helpful Mark. I have more time now if you need me to try other steps or checks. Thanks!

**Comment by mdjnelson** [comment]
Unfortunately this isn't very helpful. Somehow a certificate is still showing in your course but it has no template assigned to it. I can't replicate this.

**Comment by MomentStorm** [comment]
Sorry it wasn't more helpful. We have a bit of a suspect main Moodle install. There was an unsuccessful attempt to install malware on it in much earlier version. We cleaned that up but I always wonder if something was damaged that might account for oddities like this.

As mentioned, I was able to resolve it by reinstalling the module so all good. Let me know if I can be of any further assistance. 

[a_Cheers_sm.jpg]

[DaveFedora_StrategicCE_stacked_65x106.jpg] 
Dave Howard
Strategic Customer Education Re-Evolutionary. 
Address  Box 20007 - 3717 10th Ave N. Port Alberni, BC V9Y 8J8  
Phone  (604) 229-4409  [tel:(604) 229-4409] 
Email  dhoward@momentstorm.com [mailto:dhoward@momentstorm.com] 
Website  momentstorm.com [https://momentstorm.com]      [https://momentstorm.info/book-a-meeting] Schedule a call or meeting [https://momentstorm.info/book-a-meeting] 
“I have this radical idea that I’m not really listening unless I’m willing to be changed by you.” 

Alan Alda
Your customers want results - as quickly as possible!
Get them up to speed with your product in less than half the time! 
I'll show you how.
Helping SaaS companies increase customer LTV by creating Badass Users 

customer education | customer success | recurring revenue | saving customer time


On 6/13/2020 3:08:46 AM, Mark Nelson <notifications@github.com> wrote:
Unfortunately this isn't very helpful. Somehow a certificate is still showing in your course but it has no template assigned to it. I can't replicate this.

**Comment by mdjnelson** [comment]
Thanks @MomentStorm, no worries, I am happy you were so willing to help resolve this. I am going to close this now as I can not replicate it.
