### ISSUE TITLE
Diacritics in PDF file

### ISSUE THREAD

**Issue by cert4u** [mdjnelson/moodle-mod_customcert#335]
Hi,

at first, thanks for great modu

I have a question. When rearranging elements looks all elements in right code (diacritics is OK), but when exporting to pdf, the diacritics is ... simply wrong.

Moodle ver 3.8
Modul ver 3.8.4 (2019111804)
Language Czech

Thanks for help

**Comment by mdjnelson** [comment]
Please read https://moodle.org/mod/forum/discuss.php?d=395896, thanks.
