### ISSUE TITLE
Nothing to display

### ISSUE THREAD

**Issue by slydrone** [mdjnelson/moodle-mod_customcert#336]
When creating or duplicating a certificate, it reports that there is Recipients: 0, nothing to display. This is some sort of intermittent  fault, as now and again it does work?
moodle 3.8
Plugin 3.8.4

**Comment by mdjnelson** [comment]
Sorry, I can not replicate this. In order to fix this issue I need exactly replication steps so I can see it failing on my machine. Perhaps it is something to do with one of the elements?

**Comment by mdjnelson** [comment]
Also, why would creating a certificate pre-fill the number of Recipients?
