### ISSUE TITLE
A student name with an apostrophe in the surname causes it to go on a new line

### ISSUE THREAD

**Issue by salvamentoacademy** [mdjnelson/moodle-mod_customcert#340]
I found a problem in the printing of the certificate: if the student has a surname with the apostrophe, for example Steve D'onald, his name is printed on two lines and not on the same line.
I see the problem only 
![certificate](https://user-images.githubusercontent.com/63716740/79328829-95570800-7f0e-11ea-8f3c-4321efe39ccb.jpg)
in the student name field.
Moodle 3.8.2 (Build: 20200309) - mod_customcert 3.8.4

**Comment by mdjnelson** [comment]
I was unable to replicate this. I suspect it's the width of the student name element that is causing that. Try increase it and see if you can get it working.

**Comment by salvamentoacademy** [comment]
![Schermata 2020-04-15 alle 13 52 13](https://user-images.githubusercontent.com/63716740/79339318-9c871180-7f20-11ea-8edb-9387a01063dc.jpg)

it is not a question of length of the name, but of the text after the apostrophe, I also tried to replace the apostrophe with symbols ; ! " and it works

**Comment by mdjnelson** [comment]
Can you copy + paste the exact name they have here? Have you tried copy + pasting the name into a text editor to see if there are any special hidden characters?

**Comment by salvamentoacademy** [comment]
Hi Mark,
I discovered that it is the apostrophe symbol and depends on the Personal computer keyboard, I have two mac and this is the result, but how is this possible?
![certificato apostrofo](https://user-images.githubusercontent.com/63716740/79343688-a0b62d80-7f26-11ea-98d1-eeea81ab31ef.jpg)

**Comment by mdjnelson** [comment]
The user might be using a different keyboard/language. The solution here is to change their name to use the standard apostrophe. Is that OK?

**Comment by salvamentoacademy** [comment]
OK thank you very much
