### ISSUE TITLE
Certificate Date Field

### ISSUE THREAD

**Issue by zsnadmin** [mdjnelson/moodle-mod_customcert#341]
Please could somebody assist me with how to have this plugin use the date a student enrolled in a course for the date field as opposed to the course / completion /etc dates currently available.

Thanks Very Much

**Comment by zsnadmin** [comment]
https://github.com/mdjnelson/moodle-mod_customcert/commits?author=serg123e

THANK YOU SERG123e!!!

Copied you code in to the files and now I have a working solution!!
I really appreciate all your efforts in coding this plugin.  
Please can we include this changes in the next release ????????

**Comment by mdjnelson** [comment]
This fix is available on Moodle 3.6 onwards.

**Comment by zsnadmin** [comment]
Thanks a million not sure why but I am on version 3.8 and did not have access – I had to add it manually

 

Thanks for the quick support.

**Comment by mdjnelson** [comment]
You need to update the version of the plugin as well. The latest one for 3.8 is 3.8.4. See https://moodle.org/plugins/pluginversions.php?plugin=mod_customcert. If you are using git then do a git pull.

**Comment by zsnadmin** [comment]
Thanks Mark 

Hope to be able to repay you one day for your great assistance …… awesome to have some help.

 

Cheers
