### ISSUE TITLE
Error in Custom certificates in Moodle APP: ERROR

### ISSUE THREAD

**Issue by sunlight76** [mdjnelson/moodle-mod_customcert#342]
I have latest moodle and custom certificates plugin versions.
All is working well exept for users using Moodle app:  when students enter in Custom certificate resource to download certificate, they download it but resource is not flagged with "completed".

Result: they have the certificate but course is not marked as "completed" (because course is set to be completed only when custom certificate resource is marked as completed)

**Comment by mdjnelson** [comment]
Is the cron running on your site?

**Comment by sunlight76** [comment]
Yes it is running every 4 minutes (infact all is working including custom certificate when students use website. The problem is only with the app)

**Comment by mdjnelson** [comment]
This seems like a quick fix but I don't have the app set up and I don't have much time to work on this, so will be blindly pushing a fix. *fingers crossed*

**Comment by mdjnelson** [comment]
Ok, I am going to stop being lazy and install the app and test this first.

**Comment by mdjnelson** [comment]
Fixed, thanks for the report.
