### ISSUE TITLE
Problem with recurring certificates

### ISSUE THREAD

**Issue by praxiscare** [mdjnelson/moodle-mod_customcert#345]
I know this is probably an old issue, but I haven't seen a resolution from it. We have been using your excellent mod on our Moodle site for a number of years now but have also had a problem with dates on our certificates.

The courses we run are mandatory and need to be redone by our users annually, biannually...etc. As a result, when users redo the courses and try to print the certificate for the new attempt, they get the certificate that was generated the last time they completed the course.

Just for some background, our courses consist of a SCORM package created in Articulate Storyline which gives the user a grade for a quiz built into the SCORM package. The details of the grade...etc are then passed back to Moodle and the user then prints a certificate based on the score attained

Our workaround has been to delete the old certificate from the users account. Is there any way you could tell me where this information is stored in the Moodle database, and I can run a MariaDB script to clear down this table on an hourly basis to prevent this happening. 

We initially only used Moodle for about 10 or so courses, but with COVID-19, it's use has mushroomed and with over 1500 users regularly using it, this has become a bit of an administrative nightmare.

Any light you could shed on this would be greatly appreciated, and thanks for a great plugin,

Kind regards

John

**Comment by mdjnelson** [comment]
Closing this as it is a support question. Deferring to relevant [Moodle forum post](https://moodle.org/mod/forum/discuss.php?d=402187#p1623153).
