### ISSUE TITLE
Custom Certificate is blank

### ISSUE THREAD

**Issue by drdebsmith** [mdjnelson/moodle-mod_customcert#348]
I have saved the settings in the Plugin setup for the certificate template, but when students meet the requirements and attempt to download their certificate, it is a blank page!  I have posted to the certificate forum, but no one has responded.  Others have clearly had this problem, but I don't see anywhere that someone has posted how to resolve this.

**Comment by mdjnelson** [comment]
Have you loaded the template? Have you tried the 'Save changes and preview' button? Have you downloaded it yourself?

**Comment by drdebsmith** [comment]
The template was set up in the plugins, Activity Modules, Custom Certificate using the Manage Templates command.  It worked there and downloaded/previewed correctly.  When I added the Certificate Module to the courses, the only option I have is to edit settings.  So I set the grades students were expected to achieve to get their certificate and it downloads a blank file.  I have downloaded it so many times, and nothing changes.  Attached are the files I am getting.  I have used an older version of this plugin before with no problems.  In the courses I used it in, the same issue -- I am no longer getting a certificate with anything on it, and I haven't changed the settings.  Last year when I ran those courses the certificate option worked seamlessly.  Now, nothing.
Deb Smith 
    On Wednesday, May 13, 2020, 07:32:22 AM MDT, Mark Nelson <notifications@github.com> wrote:  
 
 


Have you loaded the template? Have you tried the 'Save changes and preview' button? Have you downloaded it yourself?

**Comment by mdjnelson** [comment]
Are you loading the template for that activity instance? Ie, going to 'Edit certificate' (*not* 'Edit settings').

<img width="574" alt="Screen Shot 2020-05-13 at 3 56 40 pm" src="https://user-images.githubusercontent.com/783213/81821661-64c8b500-9532-11ea-936b-e0983220dc7c.png">

**Comment by drdebsmith** [comment]
There is no edit certificate command within the course on Moodle 3.5.11+.  See attached.  It was added as an activity module, and those are the only commands available.  



    On Wednesday, May 13, 2020, 07:57:31 AM MDT, Mark Nelson <notifications@github.com> wrote:  
 
 


Are you loading the template for that activity instance? Ie, going to 'Edit certificate' (not 'Edit settings').

**Comment by mdjnelson** [comment]
There is no image attached. I suspect that may not be possible replying via email. This sounds like a theme issue to me where the link is being hidden. See https://moodle.org/mod/forum/discuss.php?d=388517. Look for a 'Edit certificate' link.

**Comment by drdebsmith** [comment]
Here is the screenshot.  I have forgotten the name of the theme I am using, but it is one of the very basic ones that comes with Moodle 3.5+.  It is the same theme I have used for a couple of years, and I had no certificate issues with it until I updated my certificate module.  Now it isn't working.



    On Wednesday, May 13, 2020, 08:15:08 AM MDT, Mark Nelson <notifications@github.com> wrote:  
 
 


There is no image attached. I suspect that may not be possible replying via email. This sounds like a theme issue to me where the link is being hidden. See https://moodle.org/mod/forum/discuss.php?d=388517. Look for a 'Edit certificate' link.

**Comment by drdebsmith** [comment]
Found it!  Thank you.  The answer was in the post:
Re: How to load a custom template
by Muhammad Talib -Friday, April 17, 2020, 1:54 PM
   


 On Wednesday, May 13, 2020, 08:15:08 AM MDT, Mark Nelson <notifications@github.com> wrote:  
 
 


There is no image attached. I suspect that may not be possible replying via email. This sounds like a theme issue to me where the link is being hidden. See https://moodle.org/mod/forum/discuss.php?d=388517. Look for a 'Edit certificate' link.

**Comment by mdjnelson** [comment]
Great, glad you found it! Closing.
