### ISSUE TITLE
the certificate don´t send emails

### ISSUE THREAD

**Issue by Healthinloc** [mdjnelson/moodle-mod_customcert#352]
The certificate plugin says that it sends a copy of the certificate by email to students when this option is enabled, however the same is not true.

How can I solve this?

**Comment by mdjnelson** [comment]
Please ask these support questions on the forums. You need to have the certificate setting checked, the user needs to be able to access the certificate in the course (ie they have passed all restriction settings etc) and have cron (https://docs.moodle.org/38/en/Cron) running on your site running which will trigger the task to send the certificates.
