### ISSUE TITLE
Restrict access condition

### ISSUE THREAD

**Issue by mercurialkris** [mdjnelson/moodle-mod_customcert#355]
Hi,

I have been trying to put a certain type of condition to restrict access to the custom certificate.

I am using SCORM packages and have around 6 topics with each one having a quiz of its own. Each quiz has around 10 questions. Then I have two types of certificates, one certificate of completion and one certificate of attendance.

Condition for the certificate of completion (which is working fine) is:
1) Each participant scores >70% in each module
2) Each participant completes all modules.

Condition for the certificate of attendance **(which I intend to put)** are:
1) Each participant completes all modules
2) If the participant score <70% in any module (even if participants scores less 70% in one module and more than 70% in all other modules).

**I have not been able to successfully put condition for certificate of attendance**. Please advise.

**Comment by mdjnelson** [comment]
You will need to have a look at https://docs.moodle.org/38/en/Restrict_access. The certificate itself does not handle this.
