### ISSUE TITLE
Issues with Certificates

### ISSUE THREAD

**Issue by stanakis** [mdjnelson/moodle-mod_customcert#356]
Hello all,

We have some issues with certificates.

Certificates seem that cannot be issued for some students even though they have a pass.
Certificates are issued but not showing up in course completion certificate list.
Blank grade certificate found issued when user never attempted the quiz/test.

Any ideas what could be the issue or maybe are these known issues?

Moodle version: 3.8.3
Custom certificate version: 3.8.4

Thank you all in advance

**Comment by mdjnelson** [comment]
Can you please ask these questions on the support forums?

1. This is handled by Moodle, not the certificate plugin.
2. I am not sure what the course complete certificate list is.
3. Perhaps the restriction was only put in place after this had been issued.

Thanks.
