### ISSUE TITLE
TCPPDF error

### ISSUE THREAD

**Issue by gajanaik** [mdjnelson/moodle-mod_customcert#357]
Hello Mark /
Thank you for this plugiin .. i have moodle on windows server with xamp. getting this error when i try to view the cert

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in C:\Moodle37\server\moodle\lib\tcpdf\tcpdf.php on line 7308

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1052672 bytes) in C:\Moodle37\server\moodle\cache\stores\file\lib.php on line 368

I have increased the memory_limit in php.ini to 526M .. still having this issue. 

Would you have any idea how to get around this 

Thank you 
Gaja

**Comment by mdjnelson** [comment]
Sorry, I have never encountered this issue and do not run Moodle on a Windows server. Are you able to debug what part of the code is taking so much time?

**Comment by mdjnelson** [comment]
I am guessing you may have uploaded a very large file attachment and am trying to render that.
