### ISSUE TITLE
Background image does not display when viewing in Acrobat Reader

### ISSUE THREAD

**Issue by webmarkstudios** [mdjnelson/moodle-mod_customcert#358]
Hi Mark,
I've been using the plugin without any reported issues since last year. Today a student reported that the certificates were not displaying the background image. Meanwhile a different student was able to view his certificate without a problem. 
In my testing, I was able to confirm that the image is displayed when viewing the .pdf in other (non-Adobe) programs (I tested with WPS Office and Chromebook/gmail preview) but when you try to view the same file using Adobe Acrobat reader on my Win10 desktop it does not display the background image.
In Moodle when I chose to view the certificate instead of saving it, and choose Acrobat Reader, I get an Acrobat Reader error "An error exists on this page. Acrobat may not display the page correctly, please contact the person who created the PDF document to correct the problem." 
I troubleshooted it with the template that I've been using (created last year) and I created a new certificate without a template and both times I get the same error using Adobe. When I chose a WPS Office to view it, the background image displayed without issues.
I do not use custom fonts. I am on Moodle 3.7.6 (production) and 3.7.6 (dev) both using the latest version of the plugin. The issue happens in both servers.
I would appreciate any help you can give me on this issue.
Thank you!
Amy

**Comment by mdjnelson** [comment]
This sounds like it could be an issue with the TCPDF library, rather than the custom certificate. The plugin delegates PDF generation to that library. I cant replicate the issue which makes it harder for me to fix.

**Comment by mdjnelson** [comment]
Try posting on the support forums to see if anyone else has experienced this. See https://moodle.org/mod/forum/view.php?id=7163.

**Comment by webmarkstudios** [comment]
Thanks Mark!
I went ahead and replaced the background image with a smaller, newly created and uploaded one at the individual certificate level (instead of the template) and now the .pdfs display properly in Adobe and non Adobe.
