### ISSUE TITLE
Custom course fields that are dropdowns do not display properly

### ISSUE THREAD

**Issue by StevenTsvetkov** [mdjnelson/moodle-mod_customcert#359]
Hey,

Custom course fields that are dropdowns do not display the text value of the selected dropdown option, instead, the ID number of the dropdown option is displayed. Instead of showing **Option A** or **Option B**, it displays **1** or **2**. Text and date fields behave as expected and display their content.

We are using version 2019052004.

**Comment by mdjnelson** [comment]
Thanks for the report! Feel free to provide a patch if possible (it would be much appreciated) as I am quite overwhelemed atm. Cheers!

**Comment by StevenTsvetkov** [comment]
Hey Mark,

No worries. I don't have much experience with plugin development for Moodle, however, this seems like a good issue to get started with it, so I'm willing to give it a shot sometime this week. 

Cheers!

**Comment by mdjnelson** [comment]
Closing as I have backported. 3.6 and 3.5 do not have this element so no need to cherry-pick there. Thanks!
