### ISSUE TITLE
Duplicate certificate record causes error for user and email task to fail

### ISSUE THREAD

**Issue by rayhinton** [mdjnelson/moodle-mod_customcert#363]
Moodle version: Moodle 3.7.7+ (Build: 20200717)
Plugin version: 3.7.4 (2019052004)

As far as I can tell, a duplicate certificate was created for one of our users. That is, there were two records in customcert_issues with the same userid and customcertid. This resulted in the user receiving an error when they tried to retrieve their certificate in the web interface, and the email task failing (\mod_customcert\task\email_certificate_task).

I think this is similar to the issues reported in #239, #295, and #304. I believe the changelog indicates that changes were made to prevent some instances of this issue. My understanding is that the changes were not necessarily supposed to stop duplicate certificates, but to prevent the duplicates from causing failures.

It is not very disruptive to me, since I check the task once a week, and I can resolve it quickly by deleting one of the duplicate records. But, since it was mentioned in a recent release, I thought you would be interested to see this example.

Please let me know if I can provide any other information that would be helpful. As always, thank you, Mark and all the other contributors, for your work on this very helpful plugin!

Here is the debugging message I received when I ran the email task from the command line:

```
Execute scheduled task: Handles emailing certificates. (mod_customcert\task\email_certificate_task)
... used 9837 dbqueries
... used 39.518867015839 seconds
Scheduled task failed: Handles emailing certificates. (mod_customcert\task\email_certificate_task),Multiple records found, only one record expected.
Debug info:
SELECT * FROM {customcert_issues} WHERE userid = ? AND customcertid = ?
[array (
  0 => '80139',
  1 => '5',
)]
Backtrace:
* line 1559 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
* line 1538 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 57 of /mod/customcert/element/code/classes/element.php: call to moodle_database->get_record()
* line 303 of /mod/customcert/classes/template.php: call to customcertelement_code\element->render()
* line 171 of /mod/customcert/classes/task/email_certificate_task.php: call to mod_customcert\template->generate_pdf()
* line 157 of /admin/tool/task/cli/schedule_task.php: call to mod_customcert\task\email_certificate_task->execute()
```

**Comment by mdjnelson** [comment]
Looks like another spot in `code/classes/element.php` that needs to ignore multiple certificate records. Ideally there should not be duplicates but this would be the quick fix.

**Comment by mdjnelson** [comment]
Quick fix done, closing. Cheers.

**Comment by rayhinton** [comment]
Thank you for looking at this so quickly! I really appreciate it.
