### ISSUE TITLE
missing PDF file

### ISSUE THREAD

**Issue by duanchenggui** [mdjnelson/moodle-mod_customcert#364]
Dear all,
I installed this plugin and created a certficate activity. But when previewing it says:

Missing PDF file.
PDF.js v2.5.135 (build: 8fb82e93)
Message：Missing PDF "https:/***/mod/customcert/view.php".

**Comment by mdjnelson** [comment]
I have never seen any such error before. I can only fix it if I can replicate it.

**Comment by duanchenggui** [comment]
Thanks mdjnelson， 
I've solved this issue - it's the problem of a Chrome Plugin named Salad Dictionary. 
When get it disabled, there is no such error message.
Thanks again,
Duan

**Comment by mdjnelson** [comment]
Thanks for the response. Closing.
