### ISSUE TITLE
Moodle 3.9 support?

### ISSUE THREAD

**Issue by Urpokarhu1** [mdjnelson/moodle-mod_customcert#365]
Hello,

Will this plugin support Moodle 3.9?

**Comment by gaspartessi** [comment]
i tried to install this plugin in moodle 3.9 and it is not working

**Comment by mdjnelson** [comment]
I have tested it in 3.9 and it works as expected. What was the issue?

**Comment by gaspartessi** [comment]
> I have tested it in 3.9 and it works as expected. What was the issue?

Sorry i tried again and now it is working perfectly , probably there was something wrong in my moodle test when it wasnt working

**Comment by mdjnelson** [comment]
Thanks, closing.

**Comment by Urpokarhu1** [comment]
Hello,

I don't see 3.9 supported here;

https://moodle.org/plugins/mod_customcert
