### ISSUE TITLE
Parent - security for certificate

### ISSUE THREAD

**Issue by DHusband81** [mdjnelson/moodle-mod_customcert#366]
Moodle 3.9
I have followed the Moodle guidance of setting up a Parent and assigned individuals. A parent can view their children.

I have added to the security of Parent to allow them to 'View a customer certificate'. When you view a child's certificate, it says they do not have permission.
I also tried to 'View all certificates', but this did not work.
I tried different context but it made no difference.

I did 'Capability Overview' and this reported Parent had the appropriate rights.
I viewed a Parent - 'Preferences - This user's role assignments - Check Permissions'. It said the Parent had 
    Parent in User: Patricia Bosley
    Authenticated user in System
but it did not say any settings were set for security to allow or not allow certificates were set. 

How do you let a Parent see a child's certificate? 

Thank you
David

**Comment by mdjnelson** [comment]
I have not actually ever done this myself in my whole time working with Moodle but I don't think it's an issue with the plugin. Perhaps asking on the forum is more appropriate.
