### ISSUE TITLE
Tutor allocated certificate

### ISSUE THREAD

**Issue by DHusband81** [mdjnelson/moodle-mod_customcert#367]
Moodle 3.9

Certificate set to issue via Cron task. 
- E-mail student no
- E-mail teachers no
- E-mail others yes
Certificate restricted until Activity completed.
Certificate date based on 'Activity Completed' date.

Teacher enrolled on course as per Moodle guidance.

E-mail received 'E-mail other' for the trainer. The certificate does not have an achievement date but does have a certificate code.

Reviewing the course, the list of people who have achieved a certificate does not include the tutor. It is only emailing out an incomplete certificate.

Checking the teachers profile 'My Certificates', they have been allocated a certificate.

Any ideas?

Thank you
David

**Comment by calbasi** [comment]
Maybe related:

https://github.com/mdjnelson/moodle-mod_customcert/issues/376

On my hand:

It seems this bug is not just for managers, but, in my instance, for a custom role with Student archetype BUT system context instead of student context (course and activity), enrolled users with this system custom role always receive the certificate.

**Comment by DHusband81** [comment]
Great thank you. I think that might have helped.
Now I just need to remove the certificates the tutors are listed as having in their profiles but do not show up in the course. I think I will be visiting the tables.

**Comment by mdjnelson** [comment]
Can anyone confirm whether this has been fixed with the latest code changes?

**Comment by lcaylat** [comment]
Hi Mark,
I don't know if the problem with non-editing teachers is fixed .
However, I still have the date problem. Certificates are sent with an empty completion date field.
But, if I download the certificate a few minutes later, the date is present in the PDF file. It seems that the certificates are sent too "fast". Is it possible to set a delay before sending?
Regards.

**Comment by mdjnelson** [comment]
Hi @lcaylat, unfortunately there currently is not. It's an issue with the completion date field that has been discussed many times.
