### ISSUE TITLE
Custom certificate strings missing from lang.moodle.org?

### ISSUE THREAD

**Issue by Urpokarhu1** [mdjnelson/moodle-mod_customcert#368]
Hello,

Is this a issue from Custom certificate or lang.moodle.org issue? I translated to finnish in my local Moodle 3.9 mod_customcert 3.8.4 (2019111804) following files;

- customcertelement_date.php
- customcertelement_coursefield.php
- customcertelement_digitalsignature.php
- customcertelement_qrcode.php

But I cannot upload them as a files to lang.moodle.org because I get an error ""No valid string found in the file. Make sure the file has correct filename and is properly formatted"

[](https://lang.moodle.org/mod/forum/discuss.php?d=7946#p9263)

[strings.zip](https://github.com/mdjnelson/moodle-mod_customcert/files/5054911/strings.zip)

**Comment by mdjnelson** [comment]
I just flagged the 3.8 version on plugins.moodle.org as compatible with 3.9, so I am unaware as to why it wouldn't appear. That being said I only did that recently.

**Comment by mdjnelson** [comment]
I asked @mudrd8mz about this on telegram.

**Comment by Urpokarhu1** [comment]
Hello,

David Mudrak wrote about this here (I forgot the link from the original message)

[](https://lang.moodle.org/mod/forum/discuss.php?d=7946#p9264)

**Comment by mdjnelson** [comment]
Thanks. I commented on that post.

**Comment by mdjnelson** [comment]
Closing as it is not an issue with the plugin. Spoke to David again about this.
