### ISSUE TITLE
Unknown exception related to local files

### ISSUE THREAD

**Issue by mdjnelson** [mdjnelson/moodle-mod_customcert#369]
See https://moodle.org/mod/forum/discuss.php?d=402087.

**Comment by valeriia-s** [comment]
Hi Mark! We recreated this error when we had an image element type, it had several images but no image was selected from the dropdown.

Here's an output buffer:

> Output buffer: <br /> 
<b>Notice</b>: 
Undefined property: stdClass::$filearea in 
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>427</b><br /> <br /> 
<b>Notice</b>: 
Undefined property: stdClass::$itemid in 
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>428</b><br /> <br /> 
<b>Notice</b>: 
Undefined property: stdClass::$filepath in
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>429</b><br /> <br /> 
<b>Notice</b>: Undefined property: stdClass::$filename in
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>430</b><br /> <br />
<b>Notice</b>: Undefined property: stdClass::$filearea in
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>435</b><br /> <br />
<b>Notice</b>: Undefined property: stdClass::$itemid in
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>436</b><br /> <br />
<b>Notice</b>: Undefined property: stdClass::$filepath in
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>437</b><br /> <br />
<b>Notice</b>: Undefined property: stdClass::$filename in
<b>/var/www/data/<clientsite>/public_html/moodle/mod/customcert/element/image/classes/element.php</b> on line <b>438</b><br />

**Comment by mdjnelson** [comment]
Thanks for that information!

**Comment by mdjnelson** [comment]
Creating fix now. Again, thanks for the comment. Made it easy to replicate.
