### ISSUE TITLE
Warnings on backup and restore -> need to implement get_objectid_mapping

### ISSUE THREAD

**Issue by kristian-94** [mdjnelson/moodle-mod_customcert#374]
We get this warning during a course restore that has a `mod_customcert` in it:

> 
> In order to restore course logs accurately the event "mod_customcert\event\course_module_viewed" must define the function get_objectid_mapping().
> 
>     line 550 of /lib/classes/event/base.php: call to debugging()
> 
>     line 101 of /admin/tool/log/backup/moodle2/restore_tool_log_logstore_subplugin.class.php: call to core\event\base::get_objectid_mapping()
> 
>     line 63 of /admin/tool/log/store/standard/backup/moodle2/restore_logstore_standard_subplugin.class.php: call to restore_tool_log_logstore_subplugin->process_log()
> 
>     line 137 of /backup/util/plan/restore_structure_step.class.php: call to restore_logstore_standard_subplugin->process_logstore_standard_log()
> 
>     line 112 of /backup/util/helper/restore_structure_parser_processor.class.php: call to restore_structure_step->process()
> 
>     line 178 of /backup/util/xml/parser/processors/grouped_parser_processor.class.php: call to restore_structure_parser_processor->dispatch_chunk()
> 
>     line 100 of /backup/util/helper/restore_structure_parser_processor.class.php: call to grouped_parser_processor->postprocess_chunk()
> 
>     line 148 of /backup/util/xml/parser/processors/simplified_parser_processor.class.php: call to restore_structure_parser_processor->postprocess_chunk()
> 
>     line 92 of /backup/util/xml/parser/processors/progressive_parser_processor.class.php: call to simplified_parser_processor->process_chunk()
> 
>     line 190 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser_processor->receive_chunk()
> 
>     line 278 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->publish()
> 
>     line ? of unknownfile: call to progressive_parser->end_tag()
> 
>     line 179 of /backup/util/xml/parser/progressive_parser.class.php: call to xml_parse()
> 
>     line 158 of /backup/util/xml/parser/progressive_parser.class.php: call to progressive_parser->parse()
> 
>     line 110 of /backup/util/plan/restore_structure_step.class.php: call to progressive_parser->process()
> 
>     line 181 of /backup/util/plan/base_task.class.php: call to restore_structure_step->execute()
> 
>     line 210 of /backup/moodle2/restore_activity_task.class.php: call to base_task->execute()
> 
>     line 178 of /backup/util/plan/base_plan.class.php: call to restore_activity_task->execute()
> 
>     line 168 of /backup/util/plan/restore_plan.class.php: call to base_plan->execute()
> 
>     line 377 of /backup/controller/restore_controller.class.php: call to restore_plan->execute()
> 
>     line 219 of /backup/util/ui/restore_ui.class.php: call to restore_controller->execute_plan()
> 
>     line 141 of /backup/restore.php: call to restore_ui->execute()
> 

It requires a new function implemented in our `course_module_viewed` event.

https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_38_STABLE/classes/event/course_module_viewed.php#L41

**Comment by mdjnelson** [comment]
Pushed fixed, thanks! Will backport to supported branches soon.
