### ISSUE TITLE
Moodle 3.9: Admins receive emails with custom certificates in enrolled courses without required completions

### ISSUE THREAD

**Issue by valeriia-s** [mdjnelson/moodle-mod_customcert#376]
Hello @mdjnelson,

We upgraded our Moodle site from 3.5 to 3.9 last night. When the upgrade was finished, all our admins enrolled into the courses with the custom certificate in them received an email notification with a custom certificate attached. Even though the certificate is restricted and can be received after other activities are completed.

Also, when an admin enrolls into a course with a custom certificate, they receive an email notification with a certificate attached right away even though the certificate is restricted and can be received after other activities are completed.

Other users are not affected, only admins.

Could you please look into it?

Thank you,
Valeriia

**Comment by argwallace** [comment]
I too am having the same issue but on version 3.8.4.

**Comment by mdjnelson** [comment]
I suspect this this is because of https://github.com/mdjnelson/moodle-mod_customcert/issues/270. Can you check their permissions? If you have look it used to avoid sending the certificates to anyone who could manage it, but now it is sent to those who can receive it. Maybe this should be off by default. Pinging @danmarsden.

**Comment by valeriia-s** [comment]
@mdjnelson here are the admin permissions:

<img width="768" alt="2020-09-04_1133" src="https://user-images.githubusercontent.com/29231219/92274815-c2e32480-eea2-11ea-83ce-1650189fd060.png">

**Comment by emmarichardson** [comment]
This has been an issue for some time now.  It is a big problem for us because many of our site managers also attend our trainings and they get the certificate as soon as they enroll...

**Comment by mdjnelson** [comment]
It's because they have the capability 'mod/customcert:receiveissue', either this should be set to 'No' for managers by default OR I add another check (that existed before #270) to stop sending it to people with the capability 'mod/customcert:manage'.

**Comment by mdjnelson** [comment]
The certificate will no longer email those with the capability to manage it.

**Comment by emmarichardson** [comment]
If they are also enrolled as students, will they receive it when the required activities are completed?

**Comment by mdjnelson** [comment]
With the current patch, no, they will never receive it. Do you have a situation where the user creates the certificate but can also manage it?

**Comment by emmarichardson** [comment]
It is fairly common for us at least to have managers enroll in courses as participants.  Even though they can issue themselves a certificate, it would be nice if, from their student role, they still received it if they completed all required activities like the other students in the course.

**Comment by mdjnelson** [comment]
I am going to close this issue now as it solves the main problem discussed here - managers getting emails spammed to them. I think another issue for what we have discussed now is warranted. It wouldn't be a quick fix either thinking about it.

**Comment by calbasi** [comment]
It seems this bug is not just for managers, but, in my instance, for a custom role with Student archetype BUT system context instead of student context (course and activity), enrolled users with this system custom role always receive the certificate.
