### ISSUE TITLE
Temp folder certificate creation on email task

### ISSUE THREAD

**Issue by emyb2** [mdjnelson/moodle-mod_customcert#377]
Kia ora,

Is there a reason that the generated PDF's aren't being removed after the certificates are emailed to the student? If there isn't a use for these files could they be deleted immediately after a "successful" email sent?

**Comment by mdjnelson** [comment]
I don't think this is necessary and no one has complained. The PDFs are small in size and the temporary directory is cleaned up by the cron.

**Comment by emyb2** [comment]
Kia ora Mark,

Thanks for your response. Sorry, I should have provided a wee bit of context. 

We have a client that has just over 20,000 learners, 132 custom certificate instances, and just over 16,000 custom certificate issues and have updated from the certificate to customcert. 

Before moving to custom cert there were well over 13,000 learners that had satisfied the conditions for a custom certificate issue. 

On a small scale and a new installation this is ok, but on existing installations with a large amount of learners this does take up a bit of space. 

I suppose we could set the clean up temp files cron to run daily instead of weekly for cases like this and I can safely assume that the generated custom certs don't need to stick around so they can be deleted immediately?

**Comment by mdjnelson** [comment]
A month is a long time in general for running the cron job, so yes I would say running it once a day is more suitable.

The custom certs are dynamically generated each time the user chooses to download them. Deleting a temporary one won't prevent the user from viewing it again.

Hope that answers your questions.
