### ISSUE TITLE
Add class to db/mobile.php

### ISSUE THREAD

**Issue by nguyenphuctien** [mdjnelson/moodle-mod_customcert#378]
Hi @mdjnelson,
Could you add a class to db/mobile.php ( in 'displaydata' information) so we can style for the activity in mobile app?

Thanks,

**Comment by mdjnelson** [comment]
I haven't used the mobile app or mobile desktop app in some time. Are you able to show me what the generated HTML currently is? Is there not already a unique identifier for the outer elements you could use? You can use https://paste.ofcode.org/ in order to show me the HTML that was generated.

**Comment by nguyenphuctien** [comment]
The current html is here: https://paste.ofcode.org/GX4MrFbHz65eiD6FbkVDGA
The app just put a generic class 'core-course-module-handler' into ion-item. If you have a specific class defined in mobile.php, it will appear in classes of ion-item and we can add custom css for the module's item in the app.
An example is mod/certificate: https://paste.ofcode.org/irreG3pfYnSCj9NGQDKCHE . Without put 'class' => '' in mobile.php, it generated a default class called 'core-course-module-certificate-handler' beside 'core-course-module-handler'.

I have tested it in our site and it worked. Another example is a pull request i have made for questionnair module: https://github.com/PoetOS/moodle-mod_questionnaire/pull/281

Thank you for take a look at this issue.

Regards,

**Comment by mdjnelson** [comment]
If you want to create a merge request it would make my life easier. You can do it for 3.8 and ill backport it.

**Comment by mdjnelson** [comment]
Plus you get recognition ;)

**Comment by mdjnelson** [comment]
Done.
