### ISSUE TITLE
Emails are sent out for every certificate on the site after upgrade

### ISSUE THREAD

**Issue by emmarichardson** [mdjnelson/moodle-mod_customcert#379]
On my last two upgrades of the plugin, every earned certificate on the whole site is emailed out.  Is it possible to stop this behavior?

**Comment by mdjnelson** [comment]
Is it resending the certificates to users who already have received it in the past?

**Comment by emmarichardson** [comment]
Yes, it is resending to users that have already received it.

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by mdjnelson** [comment]
Usually I would have some idea why this would be happening but right now I can't understand how this is happening just from a simple upgrade. Are you performing a backup/restore or upgrading as per usual?

**Comment by emmarichardson** [comment]
Just upgrading as usual.  Has happened on two separate sites I have this installed on.

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by emmarichardson** [comment]
I should add that I think that it might just be occurring when the site is also being upgraded - would that make more sense?

**Comment by mdjnelson** [comment]
I still can't see why this would happening.

So situation is -

1. You have a site with a custom certificate.
2. Users get emailed this.
3. Site gets upgraded and while upgrading the users from step 2 are then emailed again.

Is that correct?

**Comment by emmarichardson** [comment]
Yes.  I can’t tell you though if it is because I am upgrading custom certificate or upgrading the site…because I tend to do both things at the same time...

Emma

**Comment by mdjnelson** [comment]
If the user id exists in the `customcert_issues` table then I don't see why they get emailed again. This check https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_38_STABLE/classes/task/email_certificate_task.php#L105 here should prevent it.

**Comment by emmarichardson** [comment]
I actually just upgraded two sites to 3.9 and it did not occur - however there was no Custom Certificate upgrade so I now think that it is the Custom Certificate upgrade causing.  That we should be able to replicate.  I am very busy this week but will see if maybe I can replicate it next week.

Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037

**Comment by mdjnelson** [comment]
Hi @emmarichardson, just a note #449 might be the issue as well and it is getting looked at.

**Comment by emmarichardson** [comment]
Good news - thanks!
Emma Richardson
Distance Learning Coordinator
Direct: 719-771-4022
***@***.***

**Comment by mdjnelson** [comment]
Closing as I believe this has been fixed by #449. Please pull latest changes from the repository or wait for me to release a new version on the plugins DB (which may be a few weeks or more).
