### ISSUE TITLE
Moodle mobile completion flag is not getting marked.

### ISSUE THREAD

**Issue by badal897** [mdjnelson/moodle-mod_customcert#380]
When students enter in Custom certificate resource to download certificate, they download it but resource is not flagged with "completed".

Activity completion settings
 - User must met the following conditions i.e. user must view the certificate.

**Comment by mdjnelson** [comment]
This was fixed in https://github.com/mdjnelson/moodle-mod_customcert/issues/342 it just hasn't been pushed to https://moodle.org/plugins/.
