### ISSUE TITLE
Unknown exception related to local files (File does not exist)

### ISSUE THREAD

**Issue by hieu15** [mdjnelson/moodle-mod_customcert#381]
I have bug when i load templete customcert on Moodle 3.7.

**"Unknown exception related to local files (File does not exist)"
More information about this error**

This is the debug message :

Debug info:

Error code: storedfileproblem

Stack trace:

line 1076 of /lib/filestorage/file_storage.php: file_exception thrown
line 445 of /mod/customcert/element/image/classes/element.php: call to file_storage->create_file_from_storedfile()
line 344 of /mod/customcert/classes/template.php: call to customcertelement_image\element->copy_element()
line 74 of /mod/customcert/load_template.php: call to mod_customcert\template->copy_to_template()

Please help me fix issue.

**Comment by mdjnelson** [comment]
Thanks, but this has already been reported and just recently fixed (see https://github.com/mdjnelson/moodle-mod_customcert/issues/369). The fix is not in the plugins directory copy of the folder as I have a few more issues to do before I release a new one.

**Comment by Ikaros2901** [comment]
Apologies for opening this topic again. I am having the same problems with Moodle 4.1.6. 

 Stack trace:

    line 1119 of /lib/filestorage/file_storage.php: file_exception thrown
    line 1084 of /lib/filelib.php: call to file_storage->create_file_from_storedfile()
    line 997 of /lib/filelib.php: call to file_copy_file_to_file_area()
    line 1148 of /lib/filelib.php: call to file_merge_draft_areas()
    line 515 of /question/type/questiontypebase.php: call to file_save_draft_area_files()
    line 266 of /question/type/multianswer/questiontype.php: call to question_type->save_question()
    line 294 of /question/bank/editquestion/question.php: call to qtype_multianswer->save_question()

Is there a solution to this, as I cannot add any questions at all. 
Thank you in advance.

**Comment by mdjnelson** [comment]
The stack trace above does not touch any code in `mod/customcert` so I am not sure how this plugin would be the cause.
