### ISSUE TITLE
On some courses the certificate gets mixed up 

### ISSUE THREAD

**Issue by Wowter** [mdjnelson/moodle-mod_customcert#382]
On some courses some certificates get mixed up. Some fields are at the wrong place and also a link is added to the PDF. This template works fine in other courses. If I change to another template in this course, then this sometimes works but in other occasions not. Duplicating the template and moving to the duplicate does not help. It is all a bit random and I can not get a stable work around.

See the attachement of a correct certificate and one that is wrong.
[Project management (English)_Certificate.pdf](https://github.com/mdjnelson/moodle-mod_customcert/files/5346827/Project.management.English._Certificate.pdf)
[Projectmanagement _ projectmatig werken_Certificaat kopie.pdf](https://github.com/mdjnelson/moodle-mod_customcert/files/5346828/Projectmanagement._.projectmatig.werken_Certificaat.kopie.pdf)

**Comment by yanigelerman459** [comment]
I have the same drawback as WOWTER. In some cases the size of the background exceeds the limits of the screen and cannot adjust it, in others I manage to accommodate all the elements but when I want to see the certificate they are left in another place and in other cases it does not even allow me to drag and drop. I've been trying to build my templates for days, I also tried to start a certificate from scratch and I can't finish it.

**Comment by mdjnelson** [comment]
Closing in favour of https://github.com/mdjnelson/moodle-mod_customcert/issues/323.
