### ISSUE TITLE
Certificate does not show date

### ISSUE THREAD

**Issue by Wowter** [mdjnelson/moodle-mod_customcert#383]
Even though we placed the date field on the template, it is not shown on the certificate itself.

**Comment by mdjnelson** [comment]
It won't display if there is nothing to display. Ex. you want the completion date to be shown but the user has not completed the course, therefore there is nothing to be shown. What is the scenario in your case?

**Comment by Wowter** [comment]
This is from a list of participants who finished the course. The list was created as soon as i activated the pluginOp 14 okt. 2020, om 18:45 heeft Mark Nelson <notifications@github.com> het volgende geschreven:It won't display if there is nothing to display. Ex. you want the completion date to be shown but the user has not completed the course, therefore there is nothing to be shown. What is the scenario in your case?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Wowter** [comment]
ah yes, this is solved. The date is set to course grade and not to completion. Now it is fine.
Thanks for clarifying this.

**Comment by mdjnelson** [comment]
Great! Thanks for letting me know.
