### ISSUE TITLE
Users with system a system role geta certificate issued event if not have the requirements

### ISSUE THREAD

**Issue by calbasi** [mdjnelson/moodle-mod_customcert#385]
It seems this bug is not just for managers, but, in my instance, for a custom role with Student archetype BUT system context instead of student context (course and activity), enrolled users with this system custom role always receive the certificate, even if not have the specified requirements.

Similar issues:
#360 #367 #376

**Comment by jrojas-garrido** [comment]
this problem as reported, is currently occurring with mod_customcert 3.5.9 2018051710 version installed in moodle with Moodle 3.5.18 (Build: 20210510).

**Comment by mdjnelson** [comment]
@calbasi - Is this still an issue with the updated certificate?

**Comment by mdjnelson** [comment]
Can you log in as that user and check if the certificate is able to be viewed by them when they visit the course?

**Comment by mdjnelson** [comment]
Closing due to lack of response and I believe https://github.com/mdjnelson/moodle-mod_customcert/issues/376 addressed this.
