### ISSUE TITLE
Course grade on certificate is different to the gradebook.

### ISSUE THREAD

**Issue by Markibacsi** [mdjnelson/moodle-mod_customcert#395]
Firstly, I would like to say a big 'Thank you' for this plugin. We have been using it for a couple of years now, and it has saved us an incredible amount of admin time.

Moodle 3.8.6 (20201109)
mod_customcert - 3.8.5 (2019111805)

Situation: 
Our language courses utilise weighted grading, namely, 30% allocated from 3 speaking assessments and 70% from a final test.
The moodle gradebook/Progress report is displaying the correct/intended final Course Total irrespective of whether they completed 1, 2 or all three speaking assessments. However, the certificate element is displaying a lower course total for those students that did not receive a score in 1 or 2 of the speaking assessments.
My question is, where is Customcert pulling the Course Total value from, and is it possible for us to force it to take the value directly from gradebook?

Many thanks in anticipation

![custcert-01](https://user-images.githubusercontent.com/40423504/101752786-901c7e00-3ada-11eb-95ff-6a381ab0501c.jpg)
![custcert-02](https://user-images.githubusercontent.com/40423504/101752800-94489b80-3ada-11eb-897b-c8af5c9ce73c.jpg)

**Comment by mdjnelson** [comment]
Hey,

Thanks, I am glad you are getting some use out of it. :)

Seems there might be a bug in the logic that generates the grades. To see the logic view https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_310_STABLE/classes/element_helper.php#L509. If you can decipher what is wrong and let me know that would be much appreciated.

Regards,

Mark

**Comment by mdjnelson** [comment]
Closing and defering to #445.
