### ISSUE TITLE
Unable to run unit tests in Moodle 3.10

### ISSUE THREAD

**Issue by mudrd8mz** [mdjnelson/moodle-mod_customcert#398]
Moodle 3.10 has PHPUnit upgraded to 8.5 with a breaking change described in lib/upgrade.txt. Attempting to run unit tests that ship with the module version 3.10.0 (2020110900) leads to errors like:

```
PHP Fatal error:  Declaration of mod_customcert_element_helper_testcase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /builds/sites/sites/mod/customcert/tests/element_helper_test.php on line 393

Fatal error: Declaration of mod_customcert_element_helper_testcase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /builds/sites/sites/mod/customcert/tests/element_helper_test.php on line 393
```

**Comment by mdjnelson** [comment]
Thanks for the report. Will be addressed in next release.

**Comment by mdjnelson** [comment]
I discovered that this has been fixed by https://github.com/mdjnelson/moodle-mod_customcert/commit/b70224c0e4683df237d4ce24413701f19ee71489.
