### ISSUE TITLE
Wrong template sent in mail

### ISSUE THREAD

**Issue by sakthig** [mdjnelson/moodle-mod_customcert#402]
We have a slightly modified template to include the course name which inherits from global template. After completion of the course when we download the certificate from admin it does show proper certificate with course name. But the mail contains the unmodifed global template.

please help resolve this issue. Is there a setting that controls this ?

**Comment by mdjnelson** [comment]
Thanks for the report. I will look into this when I am preparing the next release.

**Comment by mdjnelson** [comment]
I know the solution to this (I think), will post fix soon.

**Comment by mdjnelson** [comment]
I need to set `$PAGE->set_context ..` here. Just noting for myself when preparing fix.
