### ISSUE TITLE
Show description on course page tick box

### ISSUE THREAD

**Issue by jb-fol** [mdjnelson/moodle-mod_customcert#406]
Hi - awesome plugin. Could you please consider adding the tick box to allow the certificate description to be shown on the course page, as with other activities?

**Comment by mdjnelson** [comment]
Adding to next release. Shouldn't be hard to do and I am wondering why it wasn't implemented earlier, I guess it is easy to miss.

**Comment by mdjnelson** [comment]
Code is done, will be in next release, or simply pull from github to get it now.

**Comment by jb-fol** [comment]
Thanks Mark, very much appreciated!
