### ISSUE TITLE
teachers/manager cannot open issued certificates without mod/customcert:receiveissue 

### ISSUE THREAD

**Issue by Urpokarhu1** [mdjnelson/moodle-mod_customcert#412]
Hello,

teacher/manager-role cannot open certificates that are issued to students if you don't allow mod/customcert:receiveissue if  this isn't allowed issued certificate opens up as blank white page for them.

If you enable this permission they will receive email message everytime when someone creates a certificate with setting "Email students" "yes".

This need to be fixed. @mdjnelson

**Comment by stonerl** [comment]
Should be solved by #413

**Comment by mdjnelson** [comment]
Added #413 to do as next release.

**Comment by mdjnelson** [comment]
Fixed. :)
