### ISSUE TITLE
String 'emailstudentbody' does not follow user's language setting (only system language)

### ISSUE THREAD

**Issue by harriholappa** [mdjnelson/moodle-mod_customcert#414]
Hello,

In Moodle installations with multiple language packs, the 'mod_customcert | emailstudentbody' string only uses the language version that is set up as the system default. It does not respect user's preferred language setting.

We tested this in both 3.5. and 3.9.

Thank you for the plugin!
Harri Holappa

**Comment by mdjnelson** [comment]
Thanks for the report.

If you can provide a patch that would be great.

**Comment by mdjnelson** [comment]
This might be related to https://github.com/mdjnelson/moodle-mod_customcert/issues/402.

**Comment by mdjnelson** [comment]
I know the solution to this (I think), will post fix soon.

**Comment by mdjnelson** [comment]
The solution involves using `cron_setup_user` when emailing each student.
