### ISSUE TITLE
Background Images disappear on Multiple Certificate Instances

### ISSUE THREAD

**Issue by limms7162** [mdjnelson/moodle-mod_customcert#418]
I have created 2 certificate instances in one course.  Once is a statement of attainment which has the results of the final assessment task and the other is a certificate of completion when the whole course is complete.

I have a different background image for each certificate.  When I add the specific background image for the statement of attainment version, the background image for the certificate of completion disappears and visa versa.

Are you able to have two different instances with two different background images in the one course?

Using Moodle 3.9.3

**Comment by mdjnelson** [comment]
What version of the certificate are you using? I just tried this and it worked as expected. I had two certificates in the same course with different background images.

**Comment by limms7162** [comment]
Actually worked out the problem - had to have both background images in each certificate.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdjnelson** [comment]
Ok, thanks. Closing.
