### ISSUE TITLE
Remove usage of deprecated get_extra_user_fields and user_picture::fields() and in 3.11

### ISSUE THREAD

**Issue by mdjnelson** [mdjnelson/moodle-mod_customcert#423]
```
get_extra_user_fields() is deprecated. Please use the \core_user\fields API instead.

line 3331 of /lib/deprecatedlib.php: call to debugging()
line 263 of /mod/customcert/classes/certificate.php: call to get_extra_user_fields()
line 204 of /mod/customcert/classes/report_table.php: call to mod_customcert\certificate::get_issues()
line 2091 of /lib/tablelib.php: call to mod_customcert\report_table->query_db()
line 157 of /mod/customcert/view.php: call to table_sql->out()

user_picture::fields() is deprecated. Please use the \core_user\fields API instead.

line 256 of /lib/outputcomponents.php: call to debugging()
line 264 of /mod/customcert/classes/certificate.php: call to user_picture::fields()
line 204 of /mod/customcert/classes/report_table.php: call to mod_customcert\certificate::get_issues()
line 2091 of /lib/tablelib.php: call to mod_customcert\report_table->query_db()
line 157 of /mod/customcert/view.php: call to table_sql->out()
```

From a message I was sent.

**Comment by leonstr** [comment]
And [call to deprecated `get_user_field_name()` in `classes/report_table.php`](https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_311_STABLE/classes/report_table.php#L82). Originally [reported in the forum](https://moodle.org/mod/forum/discuss.php?d=422611#p1703194).

**Comment by mdjnelson** [comment]
Thanks Leon.

**Comment by mdjnelson** [comment]
Fixed in the `MOODLE_311_STABLE` branch.

**Comment by lcassisi** [comment]
Stopped working on Moodle 4.3.3. Got this error:

Detectado un error de codificación, debe ser corregido por un programador: get_extra_user_fields() has been removed. Please use the \core_user\fields API instead.

**Comment by leonstr** [comment]
@lcassisi What [version of mod_customcert](https://docs.moodle.org/403/en/Installing_plugins#Plugins_overview) do you have installed? The current [version of mod_customcert](https://moodle.org/plugins/mod_customcert/versions) for Moodle 4.3 (2023042407) does not contain any call to `get_extra_user_fields()`. If you have this version, please [enable debugging](https://moodle.org/mod/forum/discuss.php?d=420548#p1694976) to get more details of this error.
