### ISSUE TITLE
Open Certificate in New Window

### ISSUE THREAD

**Issue by rpatel-syftco** [mdjnelson/moodle-mod_customcert#426]
I looked at issue 405 and I wanted this functionality as well.  I tried all the different options the pdflib.php, but they all do the same thing.  Do I have to restart Apache after making the change in the file?  

I basically want to open the certificate in the new window and not the same window.  We have had complaints from all the teachers/students that after viewing the certificate, the close the window and now they have to login again.  What option would that be in the pdflib.php?  

Thank you for helping.

**Comment by mdjnelson** [comment]
If the library doesn't provide that functionality by default you may need to come up with your own solution, like adding `_blank` to the submit query. See https://stackoverflow.com/questions/896724/how-to-open-a-new-window-on-form-submit.
