### ISSUE TITLE
Publishing a new 3.9 release: 3.9.1

### ISSUE THREAD

**Issue by calbasi** [mdjnelson/moodle-mod_customcert#427]
Hi,

The 3.9 has some commits since 3.9.0 release. There is at least one of them important: #412 
Considering 3.9 version is a LTS and his life cicle ended long away (2023), I think it will be useful to release a new minor version, 3.9.1 including latest commits and make it accessible from Moodle modules ecosystem

**Comment by mdjnelson** [comment]
Yep, I am planning on releasing a new version this weekend for 3.8, 3.9, 3.10 and 3.11.

**Comment by calbasi** [comment]
Thanks a lot.
