### ISSUE TITLE
Request: Add all versions to the changes.md file

### ISSUE THREAD

**Issue by danowar2k** [mdjnelson/moodle-mod_customcert#428]
I was a little bit confused when looking for the changes between versions we're updating to and from when looking at the changes.md file.

Could you add all release tags to the file? It looks like there should be a timeline (At time X release versions 1,2,3 for the different Moodle versions which have the same changes but adapted to their Moodle versions.)

For example, right now I'd have to double-check the release date of customcert 3.9.0 and look for that in the changes.md file to find which other version this corresponds to.

Or am I wrong and the different "branched" versions differ more than it seems?

**Comment by mdjnelson** [comment]
Yes, the release notes are confusing and I am awareof it. I apologise. It happens when I release two major releases at once (because I didnt get time to do them at the time they were released) then the notes get split into two major versions. I plan on addressing this in the future.
