### ISSUE TITLE
There is very limited information on the Certificate Verification screen

### ISSUE THREAD

**Issue by alihamas575** [mdjnelson/moodle-mod_customcert#430]
Hello,
When we enter the certificate verification code on the certificate verification page, it shows a warning that only the certificate is valid. This may lead to a misunderstanding.

For example, Andrew user completed the course with the certificate number XXXXXXX01 with C1 Level in English, before giving this certificate to the institution x, he opened the pdf file with a free program such as pdf exchange editor + and changed the place from C1 to A1.

The human resources manager of the workplace where he issued the certificate, Michael, wrote the certificate number XXXXXXX01 on the certificate verification screen on my website, which is under my management, and the room says "successful". But my student named Andrew changed the success of the C1 course written in the Certificate and made A1. As the site administrator, I am not aware of this and unfortunately I gave Michael wrong information.

More fields are required in the certificate validation field than just verified,

How many hours of the course, what certificate did he get, the title of the certificate etc. In fact, if possible, it would be a better approach to show the same on the site as what is written in the certificate pdf document.

Otherwise, it becomes a document that can be manipulated and misled people.

**Comment by mdjnelson** [comment]
Please do not create multiple duplicated issues.

**Comment by mdjnelson** [comment]
Duplicate at #424.

**Comment by alihamas575** [comment]
I am so sorry
