### ISSUE TITLE
Email to users with Spanish language preference being sent in English, despite updates to language packs

### ISSUE THREAD

**Issue by michael-vaughn** [mdjnelson/moodle-mod_customcert#432]
Hi all,

I don't believe this is 100% related to this report, but the response on this other report indicated we have set things up properly: https://github.com/mdjnelson/moodle-mod_customcert/issues/267 

We're using a site with multiple language packs, including English (US) and Spanish (Mexico). We've updated the following strings in the Spanish language pack: 

- mod_customcert > emailnonstudentbody
- mod_customcert > emailnonstudentbodyplaintext
- mod_customcert > emailstudentbody
- mod_customcert > emailstudentbodyplaintext

Changing these fields in the English language pack changed the body of the emails sent to learners. Changing the same fields in the Spanish language pack still results in the learners receiving the email in English, even when their language preference has been saved as Spanish. We have also purged the site caches multiple times, and confirmed it's not a browser auto-translation issue.

**Comment by mdjnelson** [comment]
Have you updated to the latest version? What version are you using? Either #402 and #412 should have fixed this and they were just patched on 3.8 onwards.

**Comment by cam-howard** [comment]
Hi Mark,

Updating to the latest version fixed this issue. It's now working great and the email message sent with the custom certificate is sent in the language specified by the user 

Michael Vaughn and I were troubleshooting this for the same site. You can now close this issue. It works as designed.

Thanks,
Cam

**Comment by mdjnelson** [comment]
Thanks for the update.
