### ISSUE TITLE
Recipients change when copying a course into another Moodle

### ISSUE THREAD

**Issue by anieminen** [mdjnelson/moodle-mod_customcert#438]
Hi,

I think we found a bug in backup/restore functions of the module, and I couldn't find an existing issue related to this.

We have copied a course with a custom certificate activity from one Moodle site to another using backup & restore. 
Custom certificate in the original course has two recipients. After creating a backup of the course with user data included and restoring the backup in the other Moodle, there are still two recipients when I open the custom certificate activity. But those users are not the same as in the original course. In the new course recipients have the same user id's as in the original one, but they are different users that aren't even course participants. The recipient users in the original course also exist in the other Moodle database, but user id's are not the same.

Moodle version: 3.9.5
Plugin version: 3.9.0 (2020061500)

**Comment by mdjnelson** [comment]
Yep, I hadn't consider backup/restore across sites. I suppose the solution here is to ignore the users when restoring to a new site. Thoughts?

**Comment by mdjnelson** [comment]
I think this was fixed by https://github.com/mdjnelson/moodle-mod_customcert/issues/449.

**Comment by anieminen** [comment]
I can confirm that this is fixed in the latest version. User id's were mapped correctly when restoring to a new site. Thanks!
