### ISSUE TITLE
Custom Certificate view button send multiple emails

### ISSUE THREAD

**Issue by shreya1796** [mdjnelson/moodle-mod_customcert#444]
Everytime the student or the admin clicks on the VIEW CERTIFICATE button as in below screenshot, an email with certificate is sent to the certificate recipent.

however it should send the email only once, when the student/user first time clicks on the view button and the other times it should only display the certificate

![image](https://user-images.githubusercontent.com/32534511/126895901-ec1ed75f-3252-490f-b5fb-4da76fe5fe20.png)

**Comment by mdjnelson** [comment]
It should only send the certificate once. It seems those users are just blank records? Do you have the contents of the database table `mdl_customcert_issues`?
