### ISSUE TITLE
Certificate - output buffer error when trying to get property 'dateitem'

### ISSUE THREAD

**Issue by DinhHien0307** [mdjnelson/moodle-mod_customcert#446]
Output buffer error when trying to get property 'dateitem' and 'dateformat'
![image](https://user-images.githubusercontent.com/32355558/127600873-ae058bf7-f55a-4827-a17f-51aa1021c0f1.png)

Step to reproduce.
1. Admin creates a certificate with the date element.
2. Backup that certificate.
3. Try to restore that certificate to another place.
4. View restored certificate for the first time and the error appear

moodle version 3.9.3

I will create a pull request to fix this

**Comment by mdjnelson** [comment]
Are you able to tell me what the value is for `$this->get_data()`?

Thanks.

**Comment by DinhHien0307** [comment]
Hi @mdjnelson,
Sorry for the delayed response,
the value for $this->get_data() is a string.
![image](https://user-images.githubusercontent.com/32355558/130550047-e6c3cc4d-141d-43b8-b520-881f5ffbcb31.png)

**Comment by mdjnelson** [comment]
Ah, well that is broken. There is a missing `"` after `-1`. I wonder how that happened ...

**Comment by mdjnelson** [comment]
Closing as I can not replicate.
