### ISSUE TITLE
View Certificate button hidden

### ISSUE THREAD

**Issue by natkennel** [mdjnelson/moodle-mod_customcert#448]
We are using Moodle 3.10 - just upgraded from 3.9 - and using the Academi theme. Now, when a user (or myself as a course creator) tries to click the "View Certificate" button for the Custom Certificate plugin, the button is hidden. I tried to see if there was anything in the html code to show why it is listed as "hidden" (see attached screenshot), but I think it has something to do with the .php file. 

Help.

![view-error](https://user-images.githubusercontent.com/88344424/127909409-fa7d8469-6f11-42f7-a8d7-c7bb42744213.png)

**Comment by mdjnelson** [comment]
No where on the PHP file does it hide the certificate button. I have a feeling this is an issue with the custom theme. If this was common occurrence there would be a lot more bugs files.

**Comment by natkennel** [comment]
I'm not using the custom theme. I was also playing with the Inspect element in the browser and found that when I uncheck the "#region-main .singlebutton .btn..." style, the button shows like it's supposed to. Can you help me find where I would correct this? Or is there, perhaps a trigger that isn't working properly? 

![image](https://user-images.githubusercontent.com/88344424/128016813-cf3cdf20-ed12-44e0-9a8b-2d77c3d98599.png)

**Comment by mdjnelson** [comment]
You stated you are using the Academi theme. From a guess I would say they have a general rule to hide buttons with the path you listed above.

**Comment by mdjnelson** [comment]
Since I can not replicate this nor has it been reported before (and an issue this large would have) makes me suspect this is a theme issue. Closing. Thanks.
