### ISSUE TITLE
Backup and restore does not store who has already received the certificate email

### ISSUE THREAD

**Issue by brendanheywood** [mdjnelson/moodle-mod_customcert#449]
There might be something related with this issue:

https://github.com/mdjnelson/moodle-mod_customcert/issues/379

**Comment by andrewmadden** [comment]
User ID's in the issue table were not being mapped to new site.

**Comment by mdjnelson** [comment]
Closing, thanks @andrewmadden. Merged into 3.9, 3.10 and 3.11.
