### ISSUE TITLE
Unicode characters

### ISSUE THREAD

**Issue by M1k3C** [mdjnelson/moodle-mod_customcert#450]
Hello,

Unicode characters such as ł appear as ? on the generated certificates.

Moodle 3.7 on plugin version 3.7.5

**Comment by mdjnelson** [comment]
Please see https://moodle.org/mod/forum/discuss.php?d=395896.

**Comment by Sunoyon** [comment]
Hi, do you have any plan to use configurable mpdf library to export pdf instead of tcpdf? tcpdf library has issues to show unicode Bangla ligature character.
