### ISSUE TITLE
Course completion emails with certificate contains "&amp" instead of "&" with courses that have an ampersand in the name

### ISSUE THREAD

**Issue by renerosser** [mdjnelson/moodle-mod_customcert#457]
Plugin is being used on Moodle 3.10 (2020110900) and 3.11 (2021051701). The issue is present when completion emails get sent out to the students where the certificates are attached to the emails. We use the per-course email settings and not the site-wide ones. Please see screenshots of emails.

<img width="604" alt="MicrosoftTeams-image (2)" src="https://user-images.githubusercontent.com/37530377/131646154-61890bcd-a6ea-44f1-b728-655a979308ac.png">

![Screenshot 2021-08-17 at 09 33 29 (1)](https://user-images.githubusercontent.com/37530377/131646223-eca5d67b-95b1-40f3-be79-b0e187f8cd23.png)

**Comment by mdjnelson** [comment]
Thanks for the report. Ill put this on the backlog. If you or anyone else is able to provide a patch that would be very welcomed.

**Comment by mdjnelson** [comment]
Yep, can replicate this.
