### ISSUE TITLE
supporting Arabic Language

### ISSUE THREAD

**Issue by jaifar530** [mdjnelson/moodle-mod_customcert#460]
When adding a course name or student name that is in Arabic language it is showing "????????? ???? ??? " 

![cus_certifi](https://user-images.githubusercontent.com/31308766/133311296-87a0bee6-b4ce-4830-b1b9-9d5ead2bc30a.jpeg)

**Comment by mdjnelson** [comment]
Please see https://moodle.org/mod/forum/discuss.php?d=395896.
