### ISSUE TITLE
Can't align center element

### ISSUE THREAD

**Issue by TrarcoJob** [mdjnelson/moodle-mod_customcert#475]
I've installed the latest version of plugin (3.11.1) on Moodle 3.11.3.

When I insert elements like coursename, userfield, code et similia, in the settings I can't align text to center.

In other version of plugin (3.11) installed on Moodle 3.9.3 there is this possibility.

![3 11 3](https://user-images.githubusercontent.com/95419363/144420574-8706af1b-e651-4080-b1f7-086d3692bcda.png)

![3 11](https://user-images.githubusercontent.com/95419363/144420690-b227b69a-7366-456b-903e-574719608d88.png)

**Comment by mdjnelson** [comment]
Are you saying that option is no longer available?

**Comment by TrarcoJob** [comment]
Yes, the alignment text option is no longer available.

In the first screenshot, the line "**Allineamento testo**" is missing.

In substitution, i can select the position of the reference point.

**Comment by mdjnelson** [comment]
It was only added recently. You need to ensure you have the latest version from GitHub.

**Comment by TrarcoJob** [comment]
Yes, I'm ensure to have the latest version (3.11.1).

![image](https://user-images.githubusercontent.com/95419363/148752950-01582e4e-8e69-4bb7-a3c8-bb13e9d14c46.png)

**Comment by mdjnelson** [comment]
Latest one is `2021051702` which contains the upgrade code that adds the alignment field. See https://github.com/mdjnelson/moodle-mod_customcert/commit/383054be3986afb1cfa0d804d467528431071cc5.

**Comment by mdjnelson** [comment]
This version is not on the plugin database, you need to clone it from GitHub.
