### ISSUE TITLE
Letters with accent marks are not rendered onto the certificate

### ISSUE THREAD

**Issue by kennethjhamba** [mdjnelson/moodle-mod_customcert#477]
User who have their names in saved in Moodle with accent marks do not have these letters show up on their certificate or sometimes they are replaced with other letters. For example "ć" does not show up or is replaced by "a" at times.

**Comment by mdjnelson** [comment]
It's an issue with the font family you are using. Please see https://moodle.org/mod/forum/discuss.php?d=395896
