### ISSUE TITLE
Invalid get_string() identifier: 'skype' or component 'moodle'

### ISSUE THREAD

**Issue by ewallah** [mdjnelson/moodle-mod_customcert#478]
Issue #423 handled the deprecated user fields in MOODLE_311_STABLE, but for some reason the Skype field was skipped.

As a result I see debugging messages:
Invalid get_string() identifier: 'skype' or component 'moodle'. Perhaps you are missing $string['skype'] = ''; in lang/en/moodle.php?

**Comment by mdjnelson** [comment]
Thanks for the report.

**Comment by AdilIqbal95** [comment]
I'm having the same issue - would you be able to provide an update on the status of this issue please? Thanks.

**Comment by mdjnelson** [comment]
Fixed in the 4.x releases.

**Comment by mdjnelson** [comment]
This was done in https://github.com/mdjnelson/moodle-mod_customcert/commit/1755bbfd1b6236e567710cf177d1a817649d8dc1.
