### ISSUE TITLE
Certificate checking via QR code

### ISSUE THREAD

**Issue by giliomeejg** [mdjnelson/moodle-mod_customcert#494]
A couple of small suggestions that will make this module super useful:

[/mod/customcert/verify_certificate.php](https://ethiopia.learn.dotrust.org/mod/customcert/verify_certificate.php)
Use a GET rather than a post so that the certificate code can be more easily added, e.g. verify_certificate.php?code=2kfjowe8lkk

For the generated QR code, send the user to the above link, with the code embedded in the GET request.

**Comment by mdjnelson** [comment]
Are you able to create a pull request for this? Thanks. :)

**Comment by mdjnelson** [comment]
You can do this now, closing.
