### ISSUE TITLE
Failing Behat Tests

### ISSUE THREAD

**Issue by dragos5436** [mdjnelson/moodle-mod_customcert#497]
Hi,

There are a few Behat tests failing for this plugin:

1. /var/www/html/mod/customcert/tests/behat/activity_options.feature:18
   Feature: Being able to correctly display options on the certificate activity edit form
   Scenario: Edit an activity as an Editing Teacher I can see all custom certificate options
```
And I navigate to "Edit settings" in current page administration: Link "Edit settings" in the current page edit menu" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

2. /var/www/html/mod/customcert/tests/behat/activity_options.feature:52
   Feature: Being able to correctly display options on the certificate activity edit form
   Scenario: Edit an activity as an Editing Teacher without required capabilities I can't see all custom certificate options
```
And I navigate to "Edit settings" in current page administration: Link "Edit settings" in the current page edit menu" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

3. /var/www/html/mod/customcert/tests/behat/verify_certificates.feature:39
   Feature: Being able to verify that a certificate is valid or not
   Scenario: Attempt to verify a certificate as a non-user
```
And I should see "Remember username": "Remember username" text was not found in the page (Behat\Mink\Exception\ExpectationException)
```

4. /var/www/html/mod/customcert/tests/behat/managing_elements.feature:29
   Feature: Being able to manage elements in a certificate template
   Scenario: Add and edit elements in a certificate template
```
And I add the element "User field" to page "1" of the "Custom certificate 1" certificate template: debugging() message/s found:
Invalid get_string() identifier: 'skype' or component 'moodle'. Perhaps you are missing $string['skype'] = ''; in lang/en/moodle.php?
line 356 of /lib/classes/string_manager_standard.php: call to debugging()
line 7339 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 665 of /user/classes/fields.php: call to get_string()
line 55 of /mod/customcert/element/userfield/classes/element.php: call to core_user\fields::get_display_name()
line 68 of /mod/customcert/classes/edit_element_form.php: call to customcertelement_userfield\element->render_form_elements()
line 214 of /lib/formslib.php: call to mod_customcert\edit_element_form->definition()
line 79 of /mod/customcert/edit_element.php: call to moodleform->__construct()
 (Exception)
```

5. /var/www/html/mod/customcert/tests/behat/managing_templates.feature:22
   Feature: Being able to manage site templates
   Scenario: Adding a site template and loading it into a course certificate
```
And I follow "Manage activities": Link matching locator "Manage activities" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

6. /var/www/html/mod/customcert/tests/behat/managing_templates.feature:70
   Feature: Being able to manage site templates
   Scenario: Deleting a site template
```
And I follow "Manage activities": Link matching locator "Manage activities" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

7. /var/www/html/mod/customcert/tests/behat/managing_templates.feature:86
   Feature: Being able to manage site templates
   Scenario: Duplicating a site template
```
And I follow "Manage activities": Link matching locator "Manage activities" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

8. /var/www/html/mod/customcert/tests/behat/show_position_x_y.feature:30
   Feature: Being able to set a site setting to determine whether or not to display the position X and Y fields
   Scenario: Adding an element with the show position X and Y setting enabled
```
And I follow "Manage activities": Link matching locator "Manage activities" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE
executed with moodlehq/moodle-docker

**Comment by mdjnelson** [comment]
Closing. I just fixed these recently. Will do a release shortly.
