### ISSUE TITLE
mod_customcert does not respect some configuration options

### ISSUE THREAD

**Issue by MikeAndMary** [mdjnelson/moodle-mod_customcert#507]
Hi Mark,

I would like to report a couple of issues I am having with both, moodle 3.14 and with v. 4:

1. on finishing a course I have your certificate send automatically to the student and to third addresses (not sure yet if a comma seperated list works, but it arrives at the address stated at the beginning of the list). Since some data changes that I expose in the certificate I don't want to allow students to download the certificate since they receive it by email but the option "Hide from students" (see attached picture) has the effect that no certificate is send, neither to a student nor to any other address.
![image](https://user-images.githubusercontent.com/90403290/182863741-cfb05ca5-5cca-48da-ae36-87f336593654.png)
This I regard as a bug and I hope you will fix it soon.
2. Alternatively, in the permissions I find View as well as Receive permission (see attached pic) which have the same wrong result though: students don't see AND don't receive the certificate.
![image](https://user-images.githubusercontent.com/90403290/182865715-81f16064-ed22-455a-85cf-79ecf58d3c7b.png)

Thank you and kind regards,
Michael

**Comment by Markibacsi** [comment]
Hi Michael

I first thought this was a bug too. But, logically, anything that is hidden from the students is considered a teacher resource. Therefore, why should it trigger the generation and sending of the certificate?
I overcame this dilemma by using the 'restrict access' options instead. Now, our certificates are issued once they reach a certain course total in the graded activities or by date - depending on the course they are enrolled on.

All the best
Marc

**Comment by MikeAndMary** [comment]
Hi again Marc,

now it worked with new option!
Sorry for the glitch.

Michael

**Comment by MikeAndMary** [comment]
Please allow another question.
By mistake I created a certificate for a test in a course in production which I cannot reset.
I cancelled the activities in the course by that student and cancelled the certificate, but as soon as cron runs again, a new certificate is issued and sent!
How I can definitvely cancel that certificate made by mistake?

Thanks and kindest regards,
Michael

**Comment by MikeAndMary** [comment]
Hi Marc,

I saw this new Availability option in your latest release and I was very hopeful, but for me it does not work:

With the option “Show on course page” the students (and eventually teachers and “Email others”) receive the certificate by mail. As soon as I choose the restricted access or “Hide from students” nobody receives a certificate, and it is just not issued in the course.
Am I doing anything wrong?

Best regards,
Michael

**Comment by james-cnz** [comment]
Hi Michael,
If you want a certificate to be e-mailed to students but not visible on the course page, I think you should be able to do this, if you have stealth activities enabled on your Moodle server, by putting the certificate in a hidden topic, and setting it to be available but not shown on the course page.  See https://docs.moodle.org/401/en/Stealth_activities

**Comment by mdjnelson** [comment]
Thanks for addressing this @james-cnz.
