### ISSUE TITLE
Non-editing teacher has mod/customcert:manage

### ISSUE THREAD

**Issue by leonstr** [mdjnelson/moodle-mod_customcert#515]
db/access.php has:

```
    'mod/customcert:manage' => array(

        'captype' => 'write',
        'contextlevel' => CONTEXT_MODULE,
        'archetypes' => array(
            'teacher' => CAP_ALLOW,
            'editingteacher' => CAP_ALLOW,
            'manager' => CAP_ALLOW
        )
    ),
```
This grants non-editing teachers access to the Edit Certificate page.

I don't think non-editing teachers should have this capability.

**Comment by mdjnelson** [comment]
Yep, I agree. I will just change it in `db/access.php` so I don't break any existing sites relying on this.
