### ISSUE TITLE
Activity title and description shown twice in Moodle 4.0

### ISSUE THREAD

**Issue by leonstr** [mdjnelson/moodle-mod_customcert#521]
The mod_customcert instance's title and description are shown twice in Moodle 4.0 on page mod/customcert/view.php?id=<ID>.

![customcert_title](https://user-images.githubusercontent.com/10348217/200126054-13293ae0-29f6-44b5-bb2f-59f3b8fddc53.png)

See also [this forum post](https://moodle.org/mod/forum/discuss.php?d=436802).

**Comment by leonstr** [comment]
Presumably this is due to MDL-72413, [see also the dev docs](https://moodledev.io/docs/devupdate#the-activity-header-class).

**Comment by leonstr** [comment]
Added PR https://github.com/mdjnelson/moodle-mod_customcert/pull/522

**Comment by leonstr** [comment]
Added PR #523 which hopefully addresses this across all affected pages.

**Comment by mdjnelson** [comment]
Thanks, cherry-picked. :)
