### ISSUE TITLE
Position of Labels are not correct in PDF

### ISSUE THREAD

**Issue by pranavpari** [mdjnelson/moodle-mod_customcert#524]
Hello, 
When I try to reposition elements, there is warning information on the top and the certificate design goes slightly up from the actual position, and when I close that warning it is back in the correct place at design time but in PDF the background is still above the correct position. Please check the attached images.
![Screenshot 2022-11-14 at 4 23 23 PM](https://user-images.githubusercontent.com/3996308/201643441-dee56156-7f3e-4cf7-90eb-b904df339bce.png)
![Screenshot 2022-11-14 at 4 23 40 PM](https://user-images.githubusercontent.com/3996308/201643491-2fcf738d-57c6-4ad5-a4e2-688ffd16bf40.png)
![Screenshot 2022-11-14 at 4 23 54 PM](https://user-images.githubusercontent.com/3996308/201643585-65fe55c3-98f3-44a0-a899-6afd19021054.png)

**Comment by mdjnelson** [comment]
I believe this was fixed by #500. Closing.
