### ISSUE TITLE
Scheduled task failed TCPDF ERROR: [Image]

### ISSUE THREAD

**Issue by lcaylat** [mdjnelson/moodle-mod_customcert#529]
Hi,
I have errors in the scheduled task logs :
```
Execute scheduled task: S’occupe d'envoyer par courriel les certificats. (mod_customcert\task\email_certificate_task)
... started 21:49:01. Current memory use 21Mo.
... used 130109 dbqueries
... used 109.72462105751 seconds
Scheduled task failed: S’occupe d'envoyer par courriel les certificats. (mod_customcert\task\email_certificate_task),TCPDF ERROR: [Image] Unable to get the size of the image: /export/data/localcache/7d288269-5482-4f06-8773-c9e796584e02/117126b9-1ec0-4ac5-8edf-8d2fc1ebaea3/target
```
How do I know which certificate activity is causing the problem?
Thanks.

**Comment by mdjnelson** [comment]
Unfortunately this would require some debugging in the task code to find out which one is failing. I suspect there is a corrupted image or an image TCPDF can not handle. If you can duplicate this on a clean install please provide the instructions and ill work on a fix.
