### ISSUE TITLE
Feature request: Option to force language of certificate

### ISSUE THREAD

**Issue by michael-milette** [mdjnelson/moodle-mod_customcert#532]
Static text can be set on a per-certificate basis. However, fields that are generated by Custom Certificate, such as dates or fields containing multi-language tagged text, always end up in UI language. This is problematic when you have a requirement to create a certificate in a language other than that of the UI. An example of this might be if you wanted to make certificates available to students for download in more than one language.

It would therefore be very useful to have a setting enabling course content editors to force the language of a certificate.

Let me know if you have any questions. A pull request adding this feature will be contributed by [Aprende Institute](https://aprende.com/) shortly.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
Hi @mdjnelson ,

Do you think you might have a chance to review and possibly integrate this new feature soon?

Best regards,

Michael

**Comment by mdjnelson** [comment]
Ill have a look next week most likely. Thanks!

**Comment by mdjnelson** [comment]
Thanks for contributing everyone. I have rebased and added it upstream. :)
