### ISSUE TITLE
When trying to verify with QR code, user is redirected to login page

### ISSUE THREAD

**Issue by baris83** [mdjnelson/moodle-mod_customcert#545]
Hi,
I realized that, on Moodle 4.1.1 setup, when trying to verify a certificate with QR code, user is redirected to login page. I've tried it with Boost and Classic themes. We have other sites which are Moodle 3.8 and 3.11 where we use custum certificates with no such issues. 

There is also another user facing this problem https://moodle.org/mod/forum/discuss.php?d=444866

Settings:
Allow anyone to verify a certificate : Yes
Allow verification of all certificates : checked

Also tried to give Guest permissions to
mod/customcert:verifycertificate
mod/customcert:verifyallcertificates

But no success

**Comment by mdjnelson** [comment]
Seems this is a 4.x issue. Thanks for reporting. Will work on it next week.

**Comment by mdjnelson** [comment]
Looking at it today as I set some time today to work on this project.

**Comment by mdjnelson** [comment]
I have a Behat test for this exact scenario. I ran all the Behat scenarios for my plugin and there are a bunch of failures. I am going to have to see what is going on with more detail to get them all working.

**Comment by davidmoralesrivera** [comment]
Hello, i have the same problem, i tryed this to avoid the redirect:  
  
when the certificate is generated and i scan the qr code, i get this link  
  
mydomain.com/mod/customcert/verify\_certificate.php?contextid=1304&code=d4LnWGduFg&qrcode=1  
  
but, if i remove "contextid=1304" for example:  
mydomain.com/mod/customcert/verify\_certificate.php?code=d4LnWGduFg&qrcode=1  
 

the redirection stops, i dont know how to remove this parameter automatically

**Comment by mdjnelson** [comment]
This is what I expected was happening @davidmoralesrivera, thanks.

**Comment by ppachas** [comment]
Hello,

To fix this issue, edit the file: /mod/customcert/element/qrcode/classes/element.php

Comment out line 161:

`// 'contextid' => $issue->contextid,`

Now the QR code generates the link without the "contextid" parameter and the user is no longer redirected to the login page.

This worked for me.

Greetings.

**Comment by mdjnelson** [comment]
Got a fix for this now. I kept thinking it was an issue on the verification page and was confused because Behat covered this but it's an issue with the QR code generating an incorrect url - doh.

**Comment by mdjnelson** [comment]
Ok, pushed fix to github. It is now in the 4.0, 4.1 and 4.2 branches. :)

**Comment by NetcrackerNTS** [comment]
Unfortunately, I see the same behavior in the 4.4.6 version of this plugin. Maybe the fix was broken again?
