### ISSUE TITLE
Cron utility functions were moved from the global namespaces to the \core\cron class.

### ISSUE THREAD

**Issue by ewallah** [mdjnelson/moodle-mod_customcert#547]
[MDL-77186](https://tracker.moodle.org/browse/MDL-77186) made changes to the cron utility functions.

So the cron_setup_user function (https://github.com/mdjnelson/moodle-mod_customcert/blob/MOODLE_400_STABLE/classes/task/email_certificate_task.php#L185) will stop working in Moodle 4.2.

**Comment by mdjnelson** [comment]
Thanks. Will look into this next week.

**Comment by mdjnelson** [comment]
Done, thanks for the report.
