### ISSUE TITLE
Maybe there should only be one background image

### ISSUE THREAD

**Issue by Julian-Tovar** [mdjnelson/moodle-mod_customcert#550]
Good day team.

I've been working on `mod_certificate`, and I was asked to code it in such a way that only one background image can be added.

So that my code doesn't fully go to waste, and maybe it can be used here, I wanted to ask, does this make sense? I think it does, because when you add a second or third background images, they stack on top of each other and hide the backgrounds below. Besides, if the user wants to compose images, they can always add an "Image" element to the certificate, to put images on top of the background image (those images can then be moved and their size can be changed).

**Comment by mdjnelson** [comment]
Ignore my previous comment. It's a sane idea just the PR needs adjusting. I left a comment there.

**Comment by mdjnelson** [comment]
Closing. We may have a certificate with multiple pages and different backgrounds for each.

**Comment by mdjnelson** [comment]
To make this sane we would have to add a check in `customcertelement_bgimage::can_add()` to check what page it was being added to and to also check if a bgimage existed. IMO it's too much effort.
