### ISSUE TITLE
Course titles not translated

### ISSUE THREAD

**Issue by oualidfouad** [mdjnelson/moodle-mod_customcert#552]
Hi,
The course titles on the certificate page do not respect the span tags nor the {mlang} of the multi_language v2. We see titles in both languages.
Is there a fix for this?
![notworking on courses with plugin](https://user-images.githubusercontent.com/19862730/234623888-012c1e81-5419-4f03-aeae-8c67526fee09.jpeg)

**Comment by mdjnelson** [comment]
This looks like a bug in Moodle as the certificate is not responsible for printing out those lines. Please file an issue at tracker.moodle.org. Thanks.
