### ISSUE TITLE
Google Flagging all certificates as potentially dangerous

### ISSUE THREAD

**Issue by WarProgrammer** [mdjnelson/moodle-mod_customcert#554]
Good morning.
Since May 1, 2023, Gmail is labeling all PDFs issued by this plugin as potentially dangerous and does not allow them to be sent by email to their accounts, neither as a sender nor as a receiver.
It seems to be a problem with the font encoding or another code parameter of the PDF.
Could you take a look at it?
Thank you

**Comment by crnfpp** [comment]
I've had the same issue yesterday and at the moment it seems solved.
It probably was an issue Google-side.
Are you still having this problem?

**Comment by WarProgrammer** [comment]
Hi,
It seems it was solved. It doesn't fail anymore.

**Comment by mdjnelson** [comment]
Closing, thanks.
