### ISSUE TITLE
Moodle 4.2 PHP 8.0.28  deprecation warning

### ISSUE THREAD

**Issue by Hootie298** [mdjnelson/moodle-mod_customcert#555]
The following warning is appearing in our log:

AH01071: Got error 'PHP message: PHP Notice: The boolean $primary is deprecated and replaced by $type, use single_button::BUTTON_PRIMARY or self::BUTTON_SECONDARY instead

line 137 of /mod/customcert/view.php: call to single_button->__construct()

**Comment by mdjnelson** [comment]
Thanks!

**Comment by mdjnelson** [comment]
Seems this will require a new branch unfortunately.

**Comment by mdjnelson** [comment]
Fixed in a new 4.2 branch. Thanks for the report.

**Comment by Hootie298** [comment]
Thank you - I downloaded the 402 branch a couple of days ago, installed, tested and and no issues encountered.
