### ISSUE TITLE
Web Services Add Function fails to load due to customcert external functions

### ISSUE THREAD

**Issue by aspark21** [mdjnelson/moodle-mod_customcert#561]
Has been discussed in the forums but not logged here - https://moodle.org/mod/forum/discuss.php?d=444398

We don't really want to uninstall customcert to be able to use Moodle web services

**Comment by mdjnelson** [comment]
Can you please provide replication steps for this as well as Moodle and the Custom certificate versions? Thanks.

**Comment by aspark21** [comment]
Hi Mark,

Go to your.moodle.site/admin/settings.php?section=externalservices
Add a service and then click on Functions, then add a Function

Moodle 4.1 (latest MOODLE_401_STABLE)
Customcert - latest MOODLE_311_STABLE -> just updating to MOODLE_401_STABLE and re-testing

**Comment by aspark21** [comment]
well upgrading the plugin seems to have fixed it doh

**Comment by mdjnelson** [comment]
Thanks for the update.
