### ISSUE TITLE
Issue with newly added events

### ISSUE THREAD

**Issue by mdjnelson** [mdjnelson/moodle-mod_customcert#564]
Thanks to @leonstr for pointing these out.

1. Creating a new certificate or template results in both a `template_created` and a `template_updated` event. The latter is a result of `add_page()` triggering both a `page_created` and a `template_updated`. Having both `template_created` and `template_updated` on creating a template doesn't make sense to me as 'create' is one action.
2. Adding a new element results in two `template_updated` events. The second one is a result of `save_page()` triggering both a `page_updated` and a `template_updated`. Again, two events -- this time the same event -- for one action feels like a bug.
3. If the certificate has more than one page and you add an element to one page then a `page_updated` is triggered for each page even though only one has been changed.
4. For the `element_*` and `page_*` events I think `get_description()` should use 'the', not 'a'/'an', e.g. _The user with id '...' updated the page with id '...'_, not _The user with id '...' updated a page with id '...'_. Trivial but the later reads wrong to me, and it seems to be what Moodle uses, e.g. for course events.

I'll try to find time to see if I can patch these in which case I'll open an issue with a PR for you to review. For 1. and 2. it's not a case of simply removing the `template_created` and `template_updated` from `add_page()` and `save_page()`, otherwise there'd be no `template_updated` when you click **+ Add page**.

**Comment by mdjnelson** [comment]
@leonstr I have pushed a commit to fix number 4.

**Comment by mdjnelson** [comment]
@leonstr I believe this is all fixed now, can you confirm? Thanks.

**Comment by leonstr** [comment]
As a first go at fixing these I've [added branch 564-401 commit 1941274](https://github.com/mdjnelson/moodle-mod_customcert/compare/MOODLE_401_STABLE...leonstr:moodle-mod_customcert:564-401?expand=1).

Another issue: I don't like that every page_updated also has a template_updated, if there's one action then two events seems wrong. Having one template_updated and one or more page_updated would make sense. I'd need to do a bit more testing to see if the template_updated could be removed from template->save_page(), i.e. does a template_created or template_updated definitely get triggered every time save_page() is called? I haven't tried to fix this.

**Comment by leonstr** [comment]
Opened a new issue for this. Sorry if my posts were noisy.

**Comment by mdjnelson** [comment]
Hi @leonstr, no problem at all. I am in the middle of moving country for a job and don't have time to work on this. Would you be able to? Cheers.

**Comment by leonstr** [comment]
I'll try! Good luck with your move.
