### ISSUE TITLE
Background images can be overriden when using different templates and more than 1 page per certificate.

### ISSUE THREAD

**Issue by darevalo1** [mdjnelson/moodle-mod_customcert#576]
Hi MDJNELSON ! and customcert team
 
We found and replicated this error on background images override automatically any background image if a certificate uses more than 1 page or if there are more than one custom certificate template with a backgrpund image element.
 
*STEPS TO REPLICATE*
Go to any custom certificate activity or go to any custom certificate template or create a new one on any course.
First Make sure you are using 1 page on the custom certificate.
Add a background element.
Click on setting element buttom action.
Select the background you want.
save changes on the certificate.
Then add a new page in the same certificate activity on option "add page".
On this new second page, click on add background element.
Click on setting element butom action
Select or upload a different background image than the 1st page.
save changes.
go a check the background element on the page 1
Watch the background element in the page 1 is now override by the background image element of the page 2.
This same situation happens with diferent templates, if we have already two diferent templates, if we upload a background image to the first template, the second template background will be override or makes the backgrpund gets blank until go to the background setting and upload the image, but this will be conflicting overiding the first template as well making unhandle this.

OBSERVED BEHAVIOR:
If we use more than 1 page per certificate activity, the background image will override or replace the background image on the others pages.

This same situation happens with diferent templates, if we have already two diferent templates, if we upload a background image to the first template, the second template background will be override or makes the backgrpund gets blank until go to the background setting and upload the image, but this will be conflicting overiding the first template as well making unhandle this.

EXPECTED BEHAVIOR:
Each page should display a different background image that we set without overriding any other background image page or template.
 
It seems in 4.1 
The drop down menu is lost or hide to choose the backgrpound elements we have uploaded on this course.
In prevoous versions like  3.10, the dropdown menu shows the elements we have uploaded, leting us choose easier the elements.

As Troubleshooting, we suggested them to create different custom cert activity for each page temporary to avoid this page problem.

Thanks mdjnelson for your time, we hope you can check this soon.
Regards

SCREENSHOTS ATTACHED:

<img width="613" alt="page 1 and 2 on 4 1" src="https://github.com/mdjnelson/moodle-mod_customcert/assets/127536959/b2036474-4207-4023-beb1-a7cf4ff03731">

<img width="761" alt="view from background element, there is no dropdownmenu and can see the image file already replaced by the scond page" src="https://github.com/mdjnelson/moodle-mod_customcert/assets/127536959/95f6cc4f-a544-4385-8c5b-6ee35295eca6">

<img width="793" alt="view from ceprev with the well displayed options and not replacing elements" src="https://github.com/mdjnelson/moodle-mod_customcert/assets/127536959/feb13a15-5fa2-441a-89fd-23c6c36dd837">

**Comment by licethrey91** [comment]
Hi @mdjnelson, 
I would appreciate it if you could provide an update.

**Comment by mdjnelson** [comment]
I have added this to the list of things I will be working on in the near future.

Please note: It is just me maintaining this project so it can take time.

**Comment by mdjnelson** [comment]
I did this.

# Create a custom certificate.
# On the first page added a BG element with image X.
# I then added the second page and added a BG element with image Y.
# When I clicked "Save changes and preview" it works as expected.

**Comment by licethrey91** [comment]
Hi @mdjnelson, 
Thanks for your answer. I tested on sites with versions 4.1.5+ and 4.1.6, the behavior is the same, as shown in the attached video.

Steps:
1. Created a custom certificate.
2.  Added a BG element with image1 on the first page.
3. Added the second page and added a BG element with image2.
4. Then I click on the "save changes and preview" button.

[Video.mov.zip](https://github.com/mdjnelson/moodle-mod_customcert/files/14026907/Video.mov.zip)

Thank you!

**Comment by mdjnelson** [comment]
Ah I think the issue I made was to upload all the images I wanted when I added it on the first page before I created the second one.

**Comment by licethrey91** [comment]
Hi Mark, 
Could you replicate it?

**Comment by mdjnelson** [comment]
I uploaded all the images I needed when I added my first BG element to the first page, then on the second page just added a BG element and then in the drop down selected the one I wanted. I havent tried the way in your demo but im pretty sure I know what is going on.

**Comment by licethrey91** [comment]
Hi Mark,
Thanks for testing, I would like to know if you have any updates on this?

Thank you!

**Comment by darevalo1** [comment]
It is not a temproary solution, it was a replication process to see the behavior of this error.
Thanks in advance @mdjnelson

**Comment by mdjnelson** [comment]
I was talking about what I mentioned above as a temporary solution. Have you tried that?

**Comment by darevalo1** [comment]
Hi @mdjnelson Oh I´m sorry, we did the test but got the same result. The image will be replaced and override the images background on each page. this still hapenning in moodle 4.1
For temporary solution, we create each page in different custom certificate activities.
Additionally, for templates we recommend to create the certificates in a level context to do not compromise the templates images overrides.

**Comment by mdjnelson** [comment]
Hello, sorry for the delay in getting to this.

I had a look at the video and can see there are some customisations on your Moodle site that is causing this. I am not sure if it is a setting somewhere or there has been custom changes to the code.

By default this is what selecting an image is like -

<img width="664" alt="Screen Shot 2024-03-13 at 12 18 05 pm" src="https://github.com/mdjnelson/moodle-mod_customcert/assets/783213/4c315a5a-d1b3-4367-924e-b2dcda983f53">

Notice here that there is a drop down to select the image. In your case there is no drop down. In Moodle when an image is dragged into the file manager it goes into a "draft" file area. You have to click 'Save changes' for it to be uploaded to the actual course area. So, what you have to do is upload the image by dragging it into the file manager, saving, then reediting the background image element again and selecting the image from the drop-down - if you try and do this in one go it doesn't work as the drop-down box has not been updated. To avoid the tedious issue of uploading then re-editing it it seems your site got rid of the drop-down and just uses whatever image was last uploaded.

On my install when I go to add a background image to the second page the image below is what is shown, as you can see the image that was added on the first background image element is also shown.

<img width="665" alt="Screen Shot 2024-03-13 at 12 22 59 pm" src="https://github.com/mdjnelson/moodle-mod_customcert/assets/783213/281b977e-2765-400a-8bd6-d510f25f2353">

Do you have a dedicated developer and are you able to find out what changes were made to your Moodle install?

**Comment by darevalo1** [comment]
Hi @mdjnelson thanks for the information:
We would like to know the version of Moodle you did this last test?

Thank in advance, regards

**Comment by darevalo1** [comment]
Hi Mdjnelson thanks for the update:
It seems this error is happening for us in Moodles 4.1, but tried on moodle 4.3 and it worked.
We will be doing some new test with the newr versions and version plugins to make sure what could be happening.
We will let you know.

**Comment by mdjnelson** [comment]
Thanks for the response. I am closing this as I could not replicate it.
