### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by tasso85** [mdjnelson/moodle-mod_customcert#578]
When trying the plugin from the mobile app, it shows an error:

`Call to undefined function mod_customcert\output\external_format_text()`

![immagine](https://github.com/mdjnelson/moodle-mod_customcert/assets/655560/f02565c6-7ea9-4362-9216-30809a06ddba)

Looking on the server, I see nothing strange in the logs.

**Comment by mdjnelson** [comment]
Fix can be located at https://github.com/dpalou/moodle-mod_customcert/commit/fa2edaba148fcb20cede1781d96dabe38b4e0c1e. Ill cherry-pick this to this project and update this issue.

**Comment by mdjnelson** [comment]
Ah, there is a PR at https://github.com/mdjnelson/moodle-mod_customcert/pull/583.

**Comment by mdjnelson** [comment]
Closing this as it duplicates #565.
