### ISSUE TITLE
Dynamic field does not appear when attempting to reposition

### ISSUE THREAD

**Issue by carlicockrell** [mdjnelson/moodle-mod_customcert#579]
On latest release of 4.0, dynamic fields do not appear so they are unable to be repositioned.

Video of issue: https://www.loom.com/share/cf117367cdc24c58a2e737fd2db5383c?sid=5a37bff0-f11c-4b4b-9062-c1da535c0eac

**Comment by carlicockrell** [comment]
Hello,

I'm wondering if there is an update to this issue as it is currently resulting in a dealbreaker in using this tool as the dynamic fields are key feature. Thank you.

**Comment by mdjnelson** [comment]
Fixed.

**Comment by carlicockrell** [comment]
@mdjnelson I apologize for asking here, but we were wondering when the directly would be updated? https://moodle.org/plugins/mod_customcert Our AWS environment populates from the community and a new version has to be pushed for us to use this as we don't pull from git (causes update errors down the road). Is it possible to get 4.0.6 added to the community? Thank you.

**Comment by mdjnelson** [comment]
Hi @carlicockrell there are a few more issues I want to deal with before doing a release. It's all planned work in the project board.
