### ISSUE TITLE
error in Totara when making new certificate

### ISSUE THREAD

**Issue by ElineVM1991** [mdjnelson/moodle-mod_customcert#580]
Hi,

We are having an error when making a new certificate in a course in Totara. 
When making a new custom certificate:

1. add a course
2. add an activity
3. add a custom certificate
4. Give certificate a name
5. Save and display

An error appears and the certificate is not made. I also am no longer in the Course.
see print screen for error code. 

Custom certificate: 3.1 release (Build: 2016052321) 2016052321
Totara: Version 17.9 
Totara PHP Version 8.0.29

Can you help us with this? 

Kind Regards, 
Eline 
![screencapture-staging-rbfa-thelearninghub-gcecc-be-course-modedit-php-2023-08-11-08_10_20](https://github.com/mdjnelson/moodle-mod_customcert/assets/142015636/56ad0a02-3c7b-4539-b656-63c1e66e8026)

**Comment by mdjnelson** [comment]
The custom certificate version 3.1 is no longer supported and is very old. I also don't use Totara so can't debug this. I suggest asking a Totara partner to look into it as I can't replicate it.
