### ISSUE TITLE
`date` element does not show correct dateitem if the date item does not exist

### ISSUE THREAD

**Issue by matthewhilton** [mdjnelson/moodle-mod_customcert#581]
E.g. if the `date` element is linked to `{"dateitem":"gradeitem:1234",...` but this does not exist in the context, it will just say 'Issued date' in the UI (because its the first item in the list), whereas if you query the database you can see the actual dateitem.

Would be good to alert the user somehow or throw an exception if this is the case.

You can end up in this situation if you made the element when it did exist, but then the grade item was deleted.

**Comment by mdjnelson** [comment]
Best solution here is to hide it imo, instead of warning users on the PDF.

**Comment by mdjnelson** [comment]
Sorry I can not replicate this. When I set them to show the date of the quiz I created it comes up fine on my PDF, then I deleted the quiz and run cron and refresh and the browser does not show these fields.

What version of Moodle and which version of the plugin are you running?
