### ISSUE TITLE
'My certificate' link shown on profile page even when you don't have necessary permissions

### ISSUE THREAD

**Issue by universityofglasgow** [mdjnelson/moodle-mod_customcert#585]
When (for example) a student looks at the profile page of another student in the course they will see a 'My certificates' link on the profile page. This is wrong in two ways...

- It's actually *their* certificates (it's the profile of another user)
- It should not be there at all, this is the profile of another student and they don't have permission.

If they click the link, they will see...

<img width="445" alt="Screenshot 2023-10-16 at 16 22 04" src="https://github.com/mdjnelson/moodle-mod_customcert/assets/5502149/a1b68839-c297-4a93-be34-ebb1fe39317c">

**Comment by mdjnelson** [comment]
Fixed, will be in next release.
