### ISSUE TITLE
Error 503 when downloading the certificate

### ISSUE THREAD

**Issue by jepoyrn** [mdjnelson/moodle-mod_customcert#590]
![error](https://github.com/mdjnelson/moodle-mod_customcert/assets/53229833/1f301598-7db7-42de-a44e-201f4d9e68b9)

When I click the download button or clicking the certificate to be downloaded, it shows ERROR 503 as per the attached screenshot. Anyone have problem with this Error when downloading the certificate? Thanks for the help. I am using Moodle 3.11.3 and the customcert (3.11.3 2021051704) version.

**Comment by mdjnelson** [comment]
This seems like a server misconfiguration as it would be brought up by now for many people if it was a code issue. Please use the support forums to debug this.
