### ISSUE TITLE
Problem mod_customcert\task\email_certificate_task not send email

### ISSUE THREAD

**Issue by MaurizioBelli** [mdjnelson/moodle-mod_customcert#598]
**My Moodle is unable to send certificates via email and returns the following problem:**

Execute scheduled task: Gestisce l'invio dei certificati via email (mod_customcert\task\email_certificate_task)
... started 02:05:01. Current memory use 19.9 MB.
Debugging increased temporarily due to faildelay of 86400
... used 48 dbqueries
... used 0.16751909255981 seconds
Scheduled task failed: Gestisce l'invio dei certificati via email (mod_customcert\task\email_certificate_task),È stato rilevato un errore di programmazione, deve essere sistemato da un programmatore: Context does not belong to any course.
Backtrace:
* line 1564 of /lib/enrollib.php: call to context->get_course_context()
* line 1478 of /lib/enrollib.php: call to get_enrolled_join()
* line 1532 of /lib/enrollib.php: call to get_enrolled_with_capabilities_join()
* line 1655 of /lib/enrollib.php: call to get_enrolled_sql()
* line 94 of /mod/customcert/classes/task/email_certificate_task.php: call to get_enrolled_users()
* line 263 of /lib/cronlib.php: call to mod_customcert\task\email_certificate_task->execute()
* line 120 of /lib/cronlib.php: call to cron_run_inner_scheduled_task()
* line 73 of /lib/cronlib.php: call to cron_run_scheduled_tasks()
* line 81 of /admin/cron.php: call to cron_run()

**In the scheduled activities I find:**
Gestisce l'invio dei certificati via email
\mod_customcert\task\email_certificate_task | Certificato personalizzatomod_customcert |   |   | Mai | martedì, 23 gennaio 2024, 16:31 | * | * | * | * | * | 60Svuota | No

Can you help me?
How can I solve it?

**Comment by mdjnelson** [comment]
Looks like there is a bug in Moodle or something strange going on with your Moodle site. Do you have any customisations? The error is coming from `get_enrolled_users()` which the certificate calls but it fails before it gets a result back which to me seems this is not an issue with the plugin. This will require someone debugging your code and seeing what they can do.

**Comment by mdjnelson** [comment]
Do a Google search for "Moodle Context does not belong to any course" and you will see some potentially helpful posts.
