### ISSUE TITLE
No element_updated/template_updated event after reposition elements

### ISSUE THREAD

**Issue by leonstr** [mdjnelson/moodle-mod_customcert#599]
Using "Reposition elements" (`mod/customcert/rearrange.php`) and clicking _Save and close_ or _Save and continue_ does not trigger any element_updated or template_updated events.

mod_customcert 2022112804 on Moodle 4.1.5+ (Build: 20230929).

**Comment by leonstr** [comment]
Added PR #600 for this.

**Comment by mdjnelson** [comment]
Push to git, thanks!
