### ISSUE TITLE
mod_customcert error when upgrading Moodle from 3.11 to 4.3

### ISSUE THREAD

**Issue by dragos5436** [mdjnelson/moodle-mod_customcert#601]
Hi,

When trying to run the upgrade for Moodle from version 3.11.18 to 4.3.2+, we are getting this following error:
![image](https://github.com/mdjnelson/moodle-mod_customcert/assets/73345838/a1e91f2d-ab67-441b-829f-45fcb2ea253b)

MySQL 8.0.35
PHP 8.0

**Comment by mdjnelson** [comment]
I will release a version that fixes this. Sorry.
