### ISSUE TITLE
mod_certificate don't work on moodle workplace mobile app

### ISSUE THREAD

**Issue by MS-edunao** [mdjnelson/moodle-mod_customcert#606]
Hello,

When attempting to access the coursecertificate module on the Moodle Workplace application, an error occurred indicating the absence of the method mod_coursercertificate/output/external_format_text().

I resolved this issue by adding the line require_once("$CFG->libdir/externallib.php") in the file mod/coursecertificate/classes/output/mobile.php.

**Comment by mdjnelson** [comment]
Closing as this was fixed in https://github.com/mdjnelson/moodle-mod_customcert/issues/565.
