### ISSUE TITLE
Missing string subplugintype_customcertelement_plural

### ISSUE THREAD

**Issue by ewallah** [mdjnelson/moodle-mod_customcert#607]
Invalid get_string() identifier: 'subplugintype_customcertelement_plural' or component 'mod_customcert'. Perhaps you are missing $string['subplugintype_customcertelement_plural'] = ''; in mod/customcert/lang/en/customcert.php

See [github workflow](https://github.com/ewallah/moodle-report_growth/actions/runs/8016948806/job/21899872798#step:26:29)

**Comment by mdjnelson** [comment]
So this only happens in the growth report or can I see it fail on a standard Moodle install?

**Comment by mdjnelson** [comment]
Added. :)
