### ISSUE TITLE
get_extra_user_fields() has been removed (Moodle 4.3.3)

### ISSUE THREAD

**Issue by lcassisi** [mdjnelson/moodle-mod_customcert#612]
Stopped working. Got this error: 

Detectado un error de codificación, debe ser corregido por un programador: get_extra_user_fields() has been removed. Please use the \core_user\fields API instead.

**Comment by mdjnelson** [comment]
Are you sure this is still an issue? I think you made need to change the version you are using. I did a grep for `get_extra_user_fields` and could not find any.

**Comment by lcassisi** [comment]
I use mod_certificate but it's the same with mod_custom_cert. I've just uninstalled customcert, so this is the debug for mod_certificate:

Detectado un error de codificación, debe ser corregido por un programador: get_extra_user_fields() has been removed. Please use the \core_user\fields API instead.

[Más información sobre este error](http://docs.moodle.org/403/es/error/debug/codingerror)

Información de depuración:
Error code: codingerror×Descartar esta notificación
Trazado de la pila (stack):
line 2774 of /lib/deprecatedlib.php: coding_exception thrown
line 451 of /mod/certificate/locallib.php: call to get_extra_user_fields()
line 106 of /mod/certificate/view.php: call to certificate_get_issues()

**Comment by mdjnelson** [comment]
These are for issues with `mod_customcert`, not `mod_certificate`. I did a grep for `get_extra_user_fields()` and it's not used anywhere so I dont think this is an issue for those who have updated.

**Comment by lcassisi** [comment]
A new update appeared when I downloaded de las version in Moodle website plugins page. Now is working fine.

This is the file in plugins page https://moodle.org/plugins/mod_customcert is mod_customcert_moodle37_2019052005.zip (v3.7.5)
That was te problem. Thank you.
