### ISSUE TITLE
Restriction by group does not work

### ISSUE THREAD

**Issue by Apsimiegojas** [mdjnelson/moodle-mod_customcert#616]
After moodle recent update, scheduled task for emailing certificates does not work correctly with group restriction.

Steps to reproduce.
1. create certificate activity with option "Email students"  set to Yes. Restrict access to group.
![Updating_Custom_certificate__Mokymų_VMA_-_Google_C_2024-05-08_15-26-31](https://github.com/mdjnelson/moodle-mod_customcert/assets/11927913/8b4f46a9-a42e-4847-8089-d11af9d9f2f6)

2. Add students to course and assign them same group as in step 1.
![Groups__Mokymų_VMA_-_Google_Chrome_2024-05-08_15-28-49](https://github.com/mdjnelson/moodle-mod_customcert/assets/11927913/e37bc54f-7346-4be6-8630-81f6066d6f5b)

3. run cron
![Certificate_activity__Mokymų_VMA_-_Google_Chrome_2024-05-08_15-29-15](https://github.com/mdjnelson/moodle-mod_customcert/assets/11927913/36aaab24-64ef-4cb5-b8e4-941cae9c7bd3)

Expected result: certificate is sent to students
Result: nothing happens.

I looked through recent changes and found out that this issue broke functionality: [MDL-79174] (https://tracker.moodle.org/browse/MDL-79174 ) 

Moodle incorrectly checks in which groups user is. Therefore group restriction does not work and $cm->uservisible returns incorrect value.

Proposed solution:
Set global $USER value to user for which we are checking visibility
Or report it to Moodle and wait for a fix.

**Comment by mdjnelson** [comment]
Thanks for the thorough report. Would you be able to comment on [MDL-79174](https://tracker.moodle.org/browse/MDL-79174), or even better create a new issue on tracker.moodle.org. It would save me the time trying to go through the code and understand what has happened vs what should happen.

**Comment by Apsimiegojas** [comment]
I created new issue: https://tracker.moodle.org/browse/MDL-81850

**Comment by mdjnelson** [comment]
Thank you @Apsimiegojas. :)

**Comment by mdjnelson** [comment]
Closing as this is a bug in Moodle which will be fixed soon. See the Moodle tracker above for more information. Thanks again @Apsimiegojas.
