### ISSUE TITLE
When disable the plugin, the "My certificates" link still shows on the Miscellaneous of user profile.

### ISSUE THREAD

**Issue by duranchen** [mdjnelson/moodle-mod_customcert#626]
On our moodle site, we decided not to use the customcert. When I disable it on the page: plugins->Activity modules->Manage activities, the "My certificates" link still shows on the Miscellaneous of user profile.
![image](https://github.com/mdjnelson/moodle-mod_customcert/assets/4253845/48657af9-23b9-443c-abee-a477a9d41354)

**Comment by mdjnelson** [comment]
Do you have `mod_certificate` installed? What does the URL look like?

**Comment by duranchen** [comment]
> Do you have `mod_certificate` installed? What does the URL look like?

No, I don't. the link looks like - https://www.mydomain.com/mod/customcert/my_certificates.php?userid=15709
![image](https://github.com/mdjnelson/moodle-mod_customcert/assets/4253845/04a9fb69-2093-4bc4-b91f-f1e6d41dcb38)

**Comment by mdjnelson** [comment]
Seems like a bug in Moodle that is still loading the URLs from plugins even though they are disabled.

I would file a bug at tracker.moodle.org with instructions on how to replicate it (feel free to use my plugin in your testing instructions).

Are you able to do this?

**Comment by duranchen** [comment]
Hi @mdjnelson ,

is it possible to do the following change to your code? 

```
function mod_customcert_myprofile_navigation(core_user\output\myprofile\tree $tree, $user, $iscurrentuser, $course) {
    // If the module is disabled, don't show it on user profile.
    global $DB;
    $modulevisible = $DB->get_record('modules', ['name' => 'customcert', 'visible' => 1]);
    if (!$modulevisible) {
            return false;
    }

    $params = [
        'userid' => $user->id
    ];
    if ($course) {
        $params['course'] = $course->id;
    }
    $url = new moodle_url('/mod/customcert/my_certificates.php', $params);
    $node = new core_user\output\myprofile\node('miscellaneous', 'mycustomcerts',
        get_string('mycertificates', 'customcert'), null, $url);
    $tree->add_node($node);
}
```

**Comment by mdjnelson** [comment]
Hi @duranchen. I think this is a bug in Moodle and an issue should be made at tracker.moodle.org with details on how to replicate this - basically install this plugin, disable it, go to  a user's profile and see that My Certificates link still displays.
