### ISSUE TITLE
Issue with Welsh circumflex

### ISSUE THREAD

**Issue by danbuntu** [mdjnelson/moodle-mod_customcert#636]
Hello

I am working on a Moodle that has English and Welsh. We have the Welsh Lang pack installed and use multilang in course titles, descriptions etc.

When exporting a certificate with 'ŵ'   (U+0175) the certificate shows a '?'. The  ŵ shows correctly in course titles, descriptions etc. When testing with the 'standard' umlauts (ä,ö,ü) the characters show correctly.

Is this something anyone has come across before, possibly with other characters?

**Comment by rickabitdigital** [comment]
Hi @danbuntu 
I would check the font being used in the PDF contains that character at the expected location in the character map.
A quick test would be to swap the output with an issue to use one of the other system installed fonts. And/or install a new font on your Moodle system, after confirming it contains the necessary character, and test PDF outputs with that.

**Comment by danbuntu** [comment]
Ahh that looks like a very good idea. I'll give it a try on Monday and
report back.

**Comment by rickabitdigital** [comment]
If you get stuck please shout - although I'm going to be pretty much off line until Wednesday. 
The font(s) used in your Moodle theme (to display the interface, courses etc) is almost guaranteed be different to the font(s) used by TCPDF for your certificate text fields. You would hope that one of the existing system fonts has the complete unicode character map (containing your 'Latin Small Letter W with circumflex) - but I haven't checked any releases to see if this is true. 
You should be able to swap the font on any relevant field and preview the certificate PDF to test quickly.  
I've always had very specific font requirements for certificate designs and therefore installed my own fonts. I must have just been lucky with fonts containing all characters required to-date!  - although I have a pre-press background so checking unicode compliance is probably something I do without thinking when considering font usage.
All the best.

**Comment by danbuntu** [comment]
Thank for your reply. 

We sorted this by switching to a different font that is almost imperceptably different from the original one but this has full support.
