### ISSUE TITLE
Using YYYY-MM-DD date format

### ISSUE THREAD

**Issue by fulldecent** [mdjnelson/moodle-mod_customcert#638]
Please use the YYYY-MM-DD date format as an option for formatting dates.

![iso_8601](https://github.com/user-attachments/assets/b520cc31-49b9-4af6-aefd-ef2d766c3d31)
![Screenshot 2024-08-21 at 11 15 18](https://github.com/user-attachments/assets/6c2a8012-c5c7-4a6c-b322-6a08cdd63e94)

**Comment by mdjnelson** [comment]
Sounds like a good idea. I am swamped atm with work so if you could create a PR and ill take a look that will be great. Thanks.

**Comment by fulldecent** [comment]
@Raza403

**Comment by fulldecent** [comment]
Hi @raza403 are we still using the plugin? Can you please send a patch upstream?

**Comment by mdjnelson** [comment]
Done.
