### ISSUE TITLE
Verify Certificate (Error) - Expiry Element

### ISSUE THREAD

**Issue by RedQon1** [mdjnelson/moodle-mod_customcert#647]
Hi Mark,

I hope you are well. I just want to say thank you for the effort and development you put into this amazing plugin.

I just wanted to report a potential bug we encountered in our testing when verifying certificates with an expiry date.
Certificates without the "Expiry" element can be verified with no issues.

Our **Moodle is currently **4.1.6+**** and **Custom Cert plugin is 4.1.6**.
You will notice when trying to verify the certificate code either through **verify_certificate.php** or **QR code**, it will give the following error (Screenshot below):
![CustomCert-Test](https://github.com/user-attachments/assets/b537716c-c4ec-4a7f-859f-ae6499cbc5ca)

As a comparison, we also were able to replicate it on a **MoodleCloud trial** (Screenshot below):
![MoodleCloud-CustomCert-Error](https://github.com/user-attachments/assets/83088fc9-b446-47b5-b3e3-60a54285fa3c)

MoodleCloud version 4.4.2 & Custom Cert plugin 4.4.1

Hopefully, I may have missed something that is a quick fix. If you need any further information or test cases, I'm more than happy to provide them.

Cheers!
Phil

**Comment by mdjnelson** [comment]
Working on a fix now.

**Comment by mdjnelson** [comment]
Fixed. :) Thanks for the report.
